import type { AuthoredCountry } from "@/types/content";

export const arCountry: AuthoredCountry = {
  code: "ar",
  slug: "argentina",
  name: "Argentina",
  flag: "🇦🇷",
  region: "Americas",
  introduction: "Argentina is known for generous wood-fired grilling, beef, chimichurri, stuffed pastries, and Italian-influenced comfort food, all often shared slowly around a table.",
  cuisineAliases: ["Argentine restaurant", "Argentijns restaurant", "Argentinian cuisine"],
  nationalDishId: "asado",
  nationalDrink: {
    name: "Malbec",
    localName: "Malbec",
    type: "wine",
    alcoholic: true,
    description: "Full-bodied Argentine Malbec is a familiar match for grilled beef.",
  },
  menu: {
    starter: {
      id: "empanadas",
      name: "Beef Empanadas",
      localName: "Empanadas de carne",
      description: "Hand pies with warmly spiced beef, onion, and olives enclosed in a crisp golden pastry.",
      category: "starter",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["dairy-free"],
      ingredients: [
        { name: "pastry discs", quantity: 400, unit: "g" },
        { name: "ground beef", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Cook the beef filling with onion and gentle spices.",
        "2. Cool it completely before filling the pastry rounds.",
        "3. Seal the edges and bake until deeply golden.",
      ],
    },
    main: {
      id: "asado",
      name: "Argentine Barbecue",
      localName: "Asado",
      description: "A widely considered Argentine centrepiece: slow-grilled beef seasoned simply over glowing coals.",
      category: "main",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["gluten-free"],
      ingredients: [
        { name: "beef ribs", quantity: 400, unit: "g" },
        { name: "coarse salt", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Build steady embers rather than cooking over flames.",
        "2. Salt the beef and place it at a gentle distance.",
        "3. Grill slowly, turning only when a crust has formed.",
      ],
      substitutions: ['Dutch sukadelappen and entrecote both work well when grilled slowly over steady heat.'],
    },
    side: {
      id: "chimichurri",
      name: "Herb Chimichurri",
      localName: "Chimichurri",
      description: "Garlic, parsley, oregano, vinegar, and oil make a sharp sauce for grilled meats.",
      category: "side",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "parsley", quantity: 400, unit: "g" },
        { name: "red wine vinegar", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Chop the herbs and garlic very finely.",
        "2. Combine with vinegar, oil, and dried oregano.",
        "3. Rest for thirty minutes so the flavours meld.",
      ],
    },
    dessert: {
      id: "alfajores",
      name: "Dulce de Leche Sandwich Cookies",
      localName: "Alfajores",
      description: "Tender cornstarch cookies joined with dulce de leche and rolled in coconut.",
      category: "dessert",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "cornstarch", quantity: 400, unit: "g" },
        { name: "dulce de leche", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Cream butter and sugar until pale and fluffy.",
        "2. Bake small tender rounds until barely coloured.",
        "3. Sandwich with dulce de leche and coat the edges.",
      ],
    },
    drink: {
      name: "Malbec",
      localName: "Malbec",
      type: "wine",
      alcoholic: true,
      description: "Full-bodied Argentine Malbec is a familiar match for grilled beef.",
    },
    moreRecipes: [
      {
        id: "milanesa",
        name: "Milanesa",
        localName: "Milanesa",
        description:
          "Breaded beef cutlets fried crisp, often served with lemon and a simple salad.",
        category: "main",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["contains-meat"],
        ingredients: [
          { name: "beef cutlets", quantity: 600, unit: "g" },
          { name: "eggs", quantity: 2, unit: "pieces" },
          { name: "breadcrumbs", quantity: 150, unit: "g" },
          { name: "lemons", quantity: 2, unit: "pieces" },
        ],
        steps: [
          "1. Pound cutlets thin and season.",
          "2. Dip in egg and breadcrumbs.",
          "3. Fry until golden and serve with lemon wedges.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Milanesa",
      },
      {
        id: "locro",
        name: "Locro Stew",
        localName: "Locro",
        description:
          "Hearty corn, bean, and squash stew with chorizo for national-day tables.",
        category: "main",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["contains-meat"],
        ingredients: [
          { name: "hominy or white corn", quantity: 300, unit: "g" },
          { name: "squash", quantity: 400, unit: "g" },
          { name: "chorizo", quantity: 200, unit: "g" },
          { name: "white beans", quantity: 200, unit: "g" },
        ],
        steps: [
          "1. Simmer soaked corn and beans until beginning to soften.",
          "2. Add squash, onion, and sliced chorizo.",
          "3. Cook until thick and stew-like; finish with paprika oil if desired.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Locro",
      },
      {
        id: "flan-dulce-de-leche",
        name: "Dulce de Leche Flan",
        localName: "Flan",
        description:
          "Vanilla custard unmoulded onto dulce de leche or caramel for a café classic.",
        category: "dessert",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["vegetarian", "gluten-free"],
        ingredients: [
          { name: "eggs", quantity: 4, unit: "pieces" },
          { name: "milk", quantity: 500, unit: "ml" },
          { name: "sugar", quantity: 150, unit: "g" },
          { name: "dulce de leche", quantity: 100, unit: "g" },
        ],
        steps: [
          "1. Coat ramekins with caramel.",
          "2. Whisk eggs, milk, sugar, and vanilla; bake in a water bath.",
          "3. Chill, unmould, and serve with dulce de leche.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Crème_caramel",
      },
    ],
  },
  status: "published",
};
