import type { AuthoredCountry } from "@/types/content";

export const bgCountry: AuthoredCountry = {
  code: "bg",
  slug: "bulgaria",
  name: "Bulgaria",
  flag: "🇧🇬",
  region: "Europe",
  introduction:
    "Bulgarian tables balance grilled meats, bright salads, brined cheese, and pastry. Yogurt, peppers, and herbs give the cooking a distinctive Balkan freshness.",
  cuisineAliases: ["Bulgarian restaurant", "Bulgaars restaurant", "Balkan restaurant"],
  nationalDishId: "kebapche",
  nationalDrink: {
    name: "Rakia",
    localName: "Ракия",
    type: "spirit",
    alcoholic: true,
    description: "A potent fruit brandy, often served with a salad before dinner.",
  },
  menu: {
    starter: {
      id: "shopska-salad",
      name: "Shopska Salad",
      localName: "Шопска салата",
      description: "Cool tomato-cucumber salad blanketed with grated white cheese.",
      category: "starter",
      servings: 4,
      prepMinutes: 15,
      cookMinutes: 0,
      difficulty: "easy",
      dietaryLabels: ["vegetarian", "gluten-free"],
      ingredients: [
        { name: "tomatoes", quantity: 500, unit: "g" },
        { name: "cucumber", quantity: 1, unit: "piece" },
        { name: "roasted red pepper", quantity: 2, unit: "pieces" },
        { name: "sirene cheese", quantity: 180, unit: "g" },
      ],
      steps: [
        "1. Dice the vegetables and combine them in a wide bowl.",
        "2. Dress with olive oil, a little vinegar, and salt.",
        "3. Grate sirene generously over the top.",
      ],
      substitutions: ["Use feta for sirene, available in Dutch supermarkets."],
    },
    main: {
      id: "kebapche",
      name: "Grilled Kebapche",
      localName: "Кебапче",
      description: "Cumin-and-pepper pork meat logs grilled with a smoky crust.",
      category: "main",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 12,
      difficulty: "easy",
      dietaryLabels: ["gluten-free"],
      ingredients: [
        { name: "ground pork", quantity: 700, unit: "g" },
        { name: "ground beef", quantity: 300, unit: "g" },
        { name: "ground cumin", quantity: 8, unit: "g" },
        { name: "black pepper", quantity: 5, unit: "g" },
        { name: "onion", quantity: 1, unit: "piece" },
      ],
      steps: [
        "1. Knead meat, grated onion, cumin, salt, and pepper until tacky; chill 30 minutes.",
        "2. Shape into eight short cylinders with wet hands.",
        "3. Grill over high heat, turning until browned and cooked through.",
      ],
      servingSuggestion: "Plate with fries, sliced onion, and lyutenitsa.",
      drinkPairing: "Rakia is a classic aperitif; cold beer works at the grill.",
    },
    side: {
      id: "lyutenitsa",
      name: "Pepper and Tomato Relish",
      localName: "Лютеница",
      description: "A thick, sweet-savory spread of roasted peppers and tomatoes.",
      category: "side",
      servings: 4,
      prepMinutes: 15,
      cookMinutes: 35,
      difficulty: "easy",
      dietaryLabels: ["vegan", "gluten-free"],
      ingredients: [
        { name: "red peppers", quantity: 500, unit: "g" },
        { name: "tomatoes", quantity: 500, unit: "g" },
        { name: "aubergine", quantity: 1, unit: "piece" },
        { name: "sunflower oil", quantity: 30, unit: "ml" },
      ],
      steps: [
        "1. Roast peppers and aubergine until collapsed; peel and chop.",
        "2. Simmer with grated tomato and oil until thick.",
        "3. Season with salt and a pinch of sugar, then cool.",
      ],
    },
    dessert: {
      id: "banitsa",
      name: "Cheese Banitsa",
      localName: "Баница",
      description: "Flaky filo layers with tangy cheese and egg.",
      category: "dessert",
      servings: 6,
      prepMinutes: 20,
      cookMinutes: 35,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "filo pastry", quantity: 250, unit: "g" },
        { name: "feta", quantity: 250, unit: "g" },
        { name: "eggs", quantity: 3, unit: "pieces" },
        { name: "yogurt", quantity: 150, unit: "g" },
      ],
      steps: [
        "1. Mix crumbled cheese, eggs, and yogurt.",
        "2. Brush filo sheets with butter, add filling, and coil into a baking dish.",
        "3. Bake at 190°C until puffed and crisp.",
      ],
    },
    drink: {
      name: "Ayran",
      localName: "Айрян",
      type: "soft-drink",
      alcoholic: false,
      description: "A salted, diluted yogurt drink that cools rich food.",
    },
    moreRecipes: [
      {
        id: "tarator",
        name: "Cold Yogurt Cucumber Soup",
        localName: "Таратор",
        description:
          "Chilled yogurt soup with cucumber, dill, garlic, and walnuts for hot Balkan days.",
        category: "starter",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["vegetarian", "gluten-free"],
        ingredients: [
          { name: "Bulgarian yogurt", quantity: 500, unit: "g" },
          { name: "cucumber", quantity: 1, unit: "piece" },
          { name: "dill", quantity: 15, unit: "g" },
          { name: "walnuts", quantity: 40, unit: "g" },
        ],
        steps: [
          "1. Grate the cucumber and squeeze out excess liquid.",
          "2. Whisk yogurt with cold water until pourable, then stir in cucumber, crushed garlic, and dill.",
          "3. Chill thoroughly and finish with chopped walnuts and a drizzle of oil.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Tarator",
      },
      {
        id: "sarmi",
        name: "Stuffed Cabbage Leaves",
        localName: "Сарми",
        description:
          "Cabbage leaves rolled around seasoned rice and minced meat, simmered gently until tender.",
        category: "main",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["contains-meat"],
        ingredients: [
          { name: "sauerkraut leaves or cabbage", quantity: 12, unit: "pieces" },
          { name: "minced pork and beef", quantity: 500, unit: "g" },
          { name: "rice", quantity: 100, unit: "g" },
          { name: "onion", quantity: 1, unit: "piece" },
        ],
        steps: [
          "1. Soften onion and mix with minced meat, rinsed rice, paprika, and salt.",
          "2. Roll spoonfuls into cabbage leaves and pack snugly in a pot.",
          "3. Cover with water or light stock and simmer until the rice is cooked through.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Sarma",
      },
      {
        id: "mekitsi",
        name: "Fried Yogurt Dough",
        localName: "Мекици",
        description:
          "Puffy yogurt fritters dusted with sugar, often eaten for breakfast with jam.",
        category: "dessert",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["vegetarian"],
        ingredients: [
          { name: "flour", quantity: 400, unit: "g" },
          { name: "yogurt", quantity: 250, unit: "g" },
          { name: "egg", quantity: 1, unit: "piece" },
          { name: "baking soda", quantity: 5, unit: "g" },
        ],
        steps: [
          "1. Mix flour, yogurt, egg, and baking soda into a soft sticky dough and rest briefly.",
          "2. Pull small pieces and stretch them thin with oiled hands.",
          "3. Fry in medium-hot oil until golden, then dust with sugar.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Mekitsa",
      },
    ],
  },
  status: "published",
};
