import type { Country } from "@/types/content";

export const bgCountry: Country = {
  code: "bg",
  slug: "bulgaria",
  name: "Bulgaria",
  flag: "🇧🇬",
  region: "Europe",
  introduction:
    "Bulgarian tables balance grilled meats, bright salads, brined cheese, and pastry. Yogurt, peppers, and herbs give the cooking a distinctive Balkan freshness.",
  cuisineAliases: ["Bulgarian restaurant", "Bulgaars restaurant", "Balkan restaurant"],
  nationalDishId: "kebapche",
  nationalDrink: {
    name: "Rakia",
    localName: "Ракия",
    type: "spirit",
    alcoholic: true,
    description: "A potent fruit brandy, often served with a salad before dinner.",
  },
  menu: {
    starter: {
      id: "shopska-salad",
      name: "Shopska Salad",
      localName: "Шопска салата",
      description: "Cool tomato-cucumber salad blanketed with grated white cheese.",
      category: "starter",
      servings: 4,
      prepMinutes: 15,
      cookMinutes: 0,
      difficulty: "easy",
      dietaryLabels: ["vegetarian", "gluten-free"],
      ingredients: [
        { name: "tomatoes", quantity: 500, unit: "g" },
        { name: "cucumber", quantity: 1, unit: "piece" },
        { name: "roasted red pepper", quantity: 2, unit: "pieces" },
        { name: "sirene cheese", quantity: 180, unit: "g" },
      ],
      steps: [
        "1. Dice the vegetables and combine them in a wide bowl.",
        "2. Dress with olive oil, a little vinegar, and salt.",
        "3. Grate sirene generously over the top.",
      ],
      substitutions: ["Use feta for sirene, available in Dutch supermarkets."],
    },
    main: {
      id: "kebapche",
      name: "Grilled Kebapche",
      localName: "Кебапче",
      description: "Cumin-and-pepper pork meat logs grilled with a smoky crust.",
      category: "main",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 12,
      difficulty: "easy",
      dietaryLabels: ["gluten-free"],
      ingredients: [
        { name: "ground pork", quantity: 700, unit: "g" },
        { name: "ground beef", quantity: 300, unit: "g" },
        { name: "ground cumin", quantity: 8, unit: "g" },
        { name: "black pepper", quantity: 5, unit: "g" },
        { name: "onion", quantity: 1, unit: "piece" },
      ],
      steps: [
        "1. Knead meat, grated onion, cumin, salt, and pepper until tacky; chill 30 minutes.",
        "2. Shape into eight short cylinders with wet hands.",
        "3. Grill over high heat, turning until browned and cooked through.",
      ],
      servingSuggestion: "Plate with fries, sliced onion, and lyutenitsa.",
      drinkPairing: "Rakia is a classic aperitif; cold beer works at the grill.",
    },
    side: {
      id: "lyutenitsa",
      name: "Pepper and Tomato Relish",
      localName: "Лютеница",
      description: "A thick, sweet-savory spread of roasted peppers and tomatoes.",
      category: "side",
      servings: 4,
      prepMinutes: 15,
      cookMinutes: 35,
      difficulty: "easy",
      dietaryLabels: ["vegan", "gluten-free"],
      ingredients: [
        { name: "red peppers", quantity: 500, unit: "g" },
        { name: "tomatoes", quantity: 500, unit: "g" },
        { name: "aubergine", quantity: 1, unit: "piece" },
        { name: "sunflower oil", quantity: 30, unit: "ml" },
      ],
      steps: [
        "1. Roast peppers and aubergine until collapsed; peel and chop.",
        "2. Simmer with grated tomato and oil until thick.",
        "3. Season with salt and a pinch of sugar, then cool.",
      ],
    },
    dessert: {
      id: "banitsa",
      name: "Cheese Banitsa",
      localName: "Баница",
      description: "Flaky filo layers with tangy cheese and egg.",
      category: "dessert",
      servings: 6,
      prepMinutes: 20,
      cookMinutes: 35,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "filo pastry", quantity: 250, unit: "g" },
        { name: "feta", quantity: 250, unit: "g" },
        { name: "eggs", quantity: 3, unit: "pieces" },
        { name: "yogurt", quantity: 150, unit: "g" },
      ],
      steps: [
        "1. Mix crumbled cheese, eggs, and yogurt.",
        "2. Brush filo sheets with butter, add filling, and coil into a baking dish.",
        "3. Bake at 190°C until puffed and crisp.",
      ],
    },
    drink: {
      name: "Ayran",
      localName: "Айрян",
      type: "soft-drink",
      alcoholic: false,
      description: "A salted, diluted yogurt drink that cools rich food.",
    },
  },
  status: "published",
};
