import type { CountryCatalogEntry } from "@/types/content";

/**
 * Intended 197-country catalog:
 * 193 UN member states + Palestine, Vatican City, Kosovo, Taiwan.
 * Only `published` entries are selectable in the picker.
 */
export const countryCatalog: CountryCatalogEntry[] = [
  {
    code: "af",
    slug: "afghanistan",
    name: "Afghanistan",
    flag: "🇦🇫",
    region: "Asia",
    status: "draft",
  },
  {
    code: "al",
    slug: "albania",
    name: "Albania",
    flag: "🇦🇱",
    region: "Europe",
    status: "draft",
  },
  {
    code: "dz",
    slug: "algeria",
    name: "Algeria",
    flag: "🇩🇿",
    region: "Africa",
    status: "draft",
  },
  {
    code: "ad",
    slug: "andorra",
    name: "Andorra",
    flag: "🇦🇩",
    region: "Europe",
    status: "draft",
  },
  {
    code: "ao",
    slug: "angola",
    name: "Angola",
    flag: "🇦🇴",
    region: "Africa",
    status: "draft",
  },
  {
    code: "ag",
    slug: "antigua-and-barbuda",
    name: "Antigua and Barbuda",
    flag: "🇦🇬",
    region: "Americas",
    status: "draft",
  },
  {
    code: "ar",
    slug: "argentina",
    name: "Argentina",
    flag: "🇦🇷",
    region: "Americas",
    status: "draft",
  },
  {
    code: "am",
    slug: "armenia",
    name: "Armenia",
    flag: "🇦🇲",
    region: "Asia",
    status: "draft",
  },
  {
    code: "au",
    slug: "australia",
    name: "Australia",
    flag: "🇦🇺",
    region: "Oceania",
    status: "draft",
  },
  {
    code: "at",
    slug: "austria",
    name: "Austria",
    flag: "🇦🇹",
    region: "Europe",
    status: "draft",
  },
  {
    code: "az",
    slug: "azerbaijan",
    name: "Azerbaijan",
    flag: "🇦🇿",
    region: "Asia",
    status: "draft",
  },
  {
    code: "bs",
    slug: "bahamas",
    name: "Bahamas",
    flag: "🇧🇸",
    region: "Americas",
    status: "draft",
  },
  {
    code: "bh",
    slug: "bahrain",
    name: "Bahrain",
    flag: "🇧🇭",
    region: "Asia",
    status: "draft",
  },
  {
    code: "bd",
    slug: "bangladesh",
    name: "Bangladesh",
    flag: "🇧🇩",
    region: "Asia",
    status: "draft",
  },
  {
    code: "bb",
    slug: "barbados",
    name: "Barbados",
    flag: "🇧🇧",
    region: "Americas",
    status: "draft",
  },
  {
    code: "by",
    slug: "belarus",
    name: "Belarus",
    flag: "🇧🇾",
    region: "Europe",
    status: "draft",
  },
  {
    code: "be",
    slug: "belgium",
    name: "Belgium",
    flag: "🇧🇪",
    region: "Europe",
    status: "draft",
  },
  {
    code: "bz",
    slug: "belize",
    name: "Belize",
    flag: "🇧🇿",
    region: "Americas",
    status: "draft",
  },
  {
    code: "bj",
    slug: "benin",
    name: "Benin",
    flag: "🇧🇯",
    region: "Africa",
    status: "draft",
  },
  {
    code: "bt",
    slug: "bhutan",
    name: "Bhutan",
    flag: "🇧🇹",
    region: "Asia",
    status: "draft",
  },
  {
    code: "bo",
    slug: "bolivia",
    name: "Bolivia",
    flag: "🇧🇴",
    region: "Americas",
    status: "draft",
  },
  {
    code: "ba",
    slug: "bosnia-and-herzegovina",
    name: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    region: "Europe",
    status: "draft",
  },
  {
    code: "bw",
    slug: "botswana",
    name: "Botswana",
    flag: "🇧🇼",
    region: "Africa",
    status: "draft",
  },
  {
    code: "br",
    slug: "brazil",
    name: "Brazil",
    flag: "🇧🇷",
    region: "Americas",
    status: "published",
  },
  {
    code: "bn",
    slug: "brunei",
    name: "Brunei",
    flag: "🇧🇳",
    region: "Asia",
    status: "draft",
  },
  {
    code: "bg",
    slug: "bulgaria",
    name: "Bulgaria",
    flag: "🇧🇬",
    region: "Europe",
    status: "published",
  },
  {
    code: "bf",
    slug: "burkina-faso",
    name: "Burkina Faso",
    flag: "🇧🇫",
    region: "Africa",
    status: "draft",
  },
  {
    code: "bi",
    slug: "burundi",
    name: "Burundi",
    flag: "🇧🇮",
    region: "Africa",
    status: "draft",
  },
  {
    code: "cv",
    slug: "cabo-verde",
    name: "Cabo Verde",
    flag: "🇨🇻",
    region: "Africa",
    status: "draft",
  },
  {
    code: "kh",
    slug: "cambodia",
    name: "Cambodia",
    flag: "🇰🇭",
    region: "Asia",
    status: "draft",
  },
  {
    code: "cm",
    slug: "cameroon",
    name: "Cameroon",
    flag: "🇨🇲",
    region: "Africa",
    status: "draft",
  },
  {
    code: "ca",
    slug: "canada",
    name: "Canada",
    flag: "🇨🇦",
    region: "Americas",
    status: "draft",
  },
  {
    code: "cf",
    slug: "central-african-republic",
    name: "Central African Republic",
    flag: "🇨🇫",
    region: "Africa",
    status: "draft",
  },
  {
    code: "td",
    slug: "chad",
    name: "Chad",
    flag: "🇹🇩",
    region: "Africa",
    status: "draft",
  },
  {
    code: "cl",
    slug: "chile",
    name: "Chile",
    flag: "🇨🇱",
    region: "Americas",
    status: "draft",
  },
  {
    code: "cn",
    slug: "china",
    name: "China",
    flag: "🇨🇳",
    region: "Asia",
    status: "draft",
  },
  {
    code: "co",
    slug: "colombia",
    name: "Colombia",
    flag: "🇨🇴",
    region: "Americas",
    status: "draft",
  },
  {
    code: "km",
    slug: "comoros",
    name: "Comoros",
    flag: "🇰🇲",
    region: "Africa",
    status: "draft",
  },
  {
    code: "cg",
    slug: "congo",
    name: "Congo",
    flag: "🇨🇬",
    region: "Africa",
    status: "draft",
  },
  {
    code: "cd",
    slug: "congo-dr",
    name: "Democratic Republic of the Congo",
    flag: "🇨🇩",
    region: "Africa",
    status: "draft",
  },
  {
    code: "cr",
    slug: "costa-rica",
    name: "Costa Rica",
    flag: "🇨🇷",
    region: "Americas",
    status: "draft",
  },
  {
    code: "ci",
    slug: "cote-divoire",
    name: "Côte d'Ivoire",
    flag: "🇨🇮",
    region: "Africa",
    status: "draft",
  },
  {
    code: "hr",
    slug: "croatia",
    name: "Croatia",
    flag: "🇭🇷",
    region: "Europe",
    status: "draft",
  },
  {
    code: "cu",
    slug: "cuba",
    name: "Cuba",
    flag: "🇨🇺",
    region: "Americas",
    status: "draft",
  },
  {
    code: "cy",
    slug: "cyprus",
    name: "Cyprus",
    flag: "🇨🇾",
    region: "Europe",
    status: "draft",
  },
  {
    code: "cz",
    slug: "czechia",
    name: "Czechia",
    flag: "🇨🇿",
    region: "Europe",
    status: "draft",
  },
  {
    code: "dk",
    slug: "denmark",
    name: "Denmark",
    flag: "🇩🇰",
    region: "Europe",
    status: "draft",
  },
  {
    code: "dj",
    slug: "djibouti",
    name: "Djibouti",
    flag: "🇩🇯",
    region: "Africa",
    status: "draft",
  },
  {
    code: "dm",
    slug: "dominica",
    name: "Dominica",
    flag: "🇩🇲",
    region: "Americas",
    status: "draft",
  },
  {
    code: "do",
    slug: "dominican-republic",
    name: "Dominican Republic",
    flag: "🇩🇴",
    region: "Americas",
    status: "draft",
  },
  {
    code: "ec",
    slug: "ecuador",
    name: "Ecuador",
    flag: "🇪🇨",
    region: "Americas",
    status: "draft",
  },
  {
    code: "eg",
    slug: "egypt",
    name: "Egypt",
    flag: "🇪🇬",
    region: "Africa",
    status: "draft",
  },
  {
    code: "sv",
    slug: "el-salvador",
    name: "El Salvador",
    flag: "🇸🇻",
    region: "Americas",
    status: "draft",
  },
  {
    code: "gq",
    slug: "equatorial-guinea",
    name: "Equatorial Guinea",
    flag: "🇬🇶",
    region: "Africa",
    status: "draft",
  },
  {
    code: "er",
    slug: "eritrea",
    name: "Eritrea",
    flag: "🇪🇷",
    region: "Africa",
    status: "draft",
  },
  {
    code: "ee",
    slug: "estonia",
    name: "Estonia",
    flag: "🇪🇪",
    region: "Europe",
    status: "draft",
  },
  {
    code: "sz",
    slug: "eswatini",
    name: "Eswatini",
    flag: "🇸🇿",
    region: "Africa",
    status: "draft",
  },
  {
    code: "et",
    slug: "ethiopia",
    name: "Ethiopia",
    flag: "🇪🇹",
    region: "Africa",
    status: "published",
  },
  {
    code: "fj",
    slug: "fiji",
    name: "Fiji",
    flag: "🇫🇯",
    region: "Oceania",
    status: "draft",
  },
  {
    code: "fi",
    slug: "finland",
    name: "Finland",
    flag: "🇫🇮",
    region: "Europe",
    status: "draft",
  },
  {
    code: "fr",
    slug: "france",
    name: "France",
    flag: "🇫🇷",
    region: "Europe",
    status: "draft",
  },
  {
    code: "ga",
    slug: "gabon",
    name: "Gabon",
    flag: "🇬🇦",
    region: "Africa",
    status: "draft",
  },
  {
    code: "gm",
    slug: "gambia",
    name: "Gambia",
    flag: "🇬🇲",
    region: "Africa",
    status: "draft",
  },
  {
    code: "ge",
    slug: "georgia",
    name: "Georgia",
    flag: "🇬🇪",
    region: "Caucasus",
    status: "published",
  },
  {
    code: "de",
    slug: "germany",
    name: "Germany",
    flag: "🇩🇪",
    region: "Europe",
    status: "draft",
  },
  {
    code: "gh",
    slug: "ghana",
    name: "Ghana",
    flag: "🇬🇭",
    region: "Africa",
    status: "draft",
  },
  {
    code: "gr",
    slug: "greece",
    name: "Greece",
    flag: "🇬🇷",
    region: "Europe",
    status: "published",
  },
  {
    code: "gd",
    slug: "grenada",
    name: "Grenada",
    flag: "🇬🇩",
    region: "Americas",
    status: "draft",
  },
  {
    code: "gt",
    slug: "guatemala",
    name: "Guatemala",
    flag: "🇬🇹",
    region: "Americas",
    status: "draft",
  },
  {
    code: "gn",
    slug: "guinea",
    name: "Guinea",
    flag: "🇬🇳",
    region: "Africa",
    status: "draft",
  },
  {
    code: "gw",
    slug: "guinea-bissau",
    name: "Guinea-Bissau",
    flag: "🇬🇼",
    region: "Africa",
    status: "draft",
  },
  {
    code: "gy",
    slug: "guyana",
    name: "Guyana",
    flag: "🇬🇾",
    region: "Americas",
    status: "draft",
  },
  {
    code: "ht",
    slug: "haiti",
    name: "Haiti",
    flag: "🇭🇹",
    region: "Americas",
    status: "draft",
  },
  {
    code: "hn",
    slug: "honduras",
    name: "Honduras",
    flag: "🇭🇳",
    region: "Americas",
    status: "draft",
  },
  {
    code: "hu",
    slug: "hungary",
    name: "Hungary",
    flag: "🇭🇺",
    region: "Europe",
    status: "draft",
  },
  {
    code: "is",
    slug: "iceland",
    name: "Iceland",
    flag: "🇮🇸",
    region: "Europe",
    status: "draft",
  },
  {
    code: "in",
    slug: "india",
    name: "India",
    flag: "🇮🇳",
    region: "Asia",
    status: "published",
  },
  {
    code: "id",
    slug: "indonesia",
    name: "Indonesia",
    flag: "🇮🇩",
    region: "Asia",
    status: "published",
  },
  { code: "ir", slug: "iran", name: "Iran", flag: "🇮🇷", region: "Asia", status: "draft" },
  { code: "iq", slug: "iraq", name: "Iraq", flag: "🇮🇶", region: "Asia", status: "draft" },
  {
    code: "ie",
    slug: "ireland",
    name: "Ireland",
    flag: "🇮🇪",
    region: "Europe",
    status: "draft",
  },
  {
    code: "il",
    slug: "israel",
    name: "Israel",
    flag: "🇮🇱",
    region: "Asia",
    status: "draft",
  },
  {
    code: "it",
    slug: "italy",
    name: "Italy",
    flag: "🇮🇹",
    region: "Europe",
    status: "published",
  },
  {
    code: "jm",
    slug: "jamaica",
    name: "Jamaica",
    flag: "🇯🇲",
    region: "Americas",
    status: "published",
  },
  {
    code: "jp",
    slug: "japan",
    name: "Japan",
    flag: "🇯🇵",
    region: "Asia",
    status: "published",
  },
  {
    code: "jo",
    slug: "jordan",
    name: "Jordan",
    flag: "🇯🇴",
    region: "Asia",
    status: "draft",
  },
  {
    code: "kz",
    slug: "kazakhstan",
    name: "Kazakhstan",
    flag: "🇰🇿",
    region: "Asia",
    status: "draft",
  },
  {
    code: "ke",
    slug: "kenya",
    name: "Kenya",
    flag: "🇰🇪",
    region: "Africa",
    status: "published",
  },
  {
    code: "ki",
    slug: "kiribati",
    name: "Kiribati",
    flag: "🇰🇮",
    region: "Oceania",
    status: "draft",
  },
  {
    code: "kp",
    slug: "north-korea",
    name: "North Korea",
    flag: "🇰🇵",
    region: "Asia",
    status: "draft",
  },
  {
    code: "kr",
    slug: "south-korea",
    name: "South Korea",
    flag: "🇰🇷",
    region: "Asia",
    status: "draft",
  },
  {
    code: "xk",
    slug: "kosovo",
    name: "Kosovo",
    flag: "🇽🇰",
    region: "Europe",
    status: "draft",
  },
  {
    code: "kw",
    slug: "kuwait",
    name: "Kuwait",
    flag: "🇰🇼",
    region: "Asia",
    status: "draft",
  },
  {
    code: "kg",
    slug: "kyrgyzstan",
    name: "Kyrgyzstan",
    flag: "🇰🇬",
    region: "Asia",
    status: "draft",
  },
  { code: "la", slug: "laos", name: "Laos", flag: "🇱🇦", region: "Asia", status: "draft" },
  {
    code: "lv",
    slug: "latvia",
    name: "Latvia",
    flag: "🇱🇻",
    region: "Europe",
    status: "draft",
  },
  {
    code: "lb",
    slug: "lebanon",
    name: "Lebanon",
    flag: "🇱🇧",
    region: "Middle East",
    status: "published",
  },
  {
    code: "ls",
    slug: "lesotho",
    name: "Lesotho",
    flag: "🇱🇸",
    region: "Africa",
    status: "draft",
  },
  {
    code: "lr",
    slug: "liberia",
    name: "Liberia",
    flag: "🇱🇷",
    region: "Africa",
    status: "draft",
  },
  {
    code: "ly",
    slug: "libya",
    name: "Libya",
    flag: "🇱🇾",
    region: "Africa",
    status: "draft",
  },
  {
    code: "li",
    slug: "liechtenstein",
    name: "Liechtenstein",
    flag: "🇱🇮",
    region: "Europe",
    status: "draft",
  },
  {
    code: "lt",
    slug: "lithuania",
    name: "Lithuania",
    flag: "🇱🇹",
    region: "Europe",
    status: "draft",
  },
  {
    code: "lu",
    slug: "luxembourg",
    name: "Luxembourg",
    flag: "🇱🇺",
    region: "Europe",
    status: "draft",
  },
  {
    code: "mg",
    slug: "madagascar",
    name: "Madagascar",
    flag: "🇲🇬",
    region: "Africa",
    status: "draft",
  },
  {
    code: "mw",
    slug: "malawi",
    name: "Malawi",
    flag: "🇲🇼",
    region: "Africa",
    status: "draft",
  },
  {
    code: "my",
    slug: "malaysia",
    name: "Malaysia",
    flag: "🇲🇾",
    region: "Asia",
    status: "draft",
  },
  {
    code: "mv",
    slug: "maldives",
    name: "Maldives",
    flag: "🇲🇻",
    region: "Asia",
    status: "draft",
  },
  {
    code: "ml",
    slug: "mali",
    name: "Mali",
    flag: "🇲🇱",
    region: "Africa",
    status: "draft",
  },
  {
    code: "mt",
    slug: "malta",
    name: "Malta",
    flag: "🇲🇹",
    region: "Europe",
    status: "draft",
  },
  {
    code: "mh",
    slug: "marshall-islands",
    name: "Marshall Islands",
    flag: "🇲🇭",
    region: "Oceania",
    status: "draft",
  },
  {
    code: "mr",
    slug: "mauritania",
    name: "Mauritania",
    flag: "🇲🇷",
    region: "Africa",
    status: "draft",
  },
  {
    code: "mu",
    slug: "mauritius",
    name: "Mauritius",
    flag: "🇲🇺",
    region: "Africa",
    status: "draft",
  },
  {
    code: "mx",
    slug: "mexico",
    name: "Mexico",
    flag: "🇲🇽",
    region: "Americas",
    status: "published",
  },
  {
    code: "fm",
    slug: "micronesia",
    name: "Micronesia",
    flag: "🇫🇲",
    region: "Oceania",
    status: "draft",
  },
  {
    code: "md",
    slug: "moldova",
    name: "Moldova",
    flag: "🇲🇩",
    region: "Europe",
    status: "draft",
  },
  {
    code: "mc",
    slug: "monaco",
    name: "Monaco",
    flag: "🇲🇨",
    region: "Europe",
    status: "draft",
  },
  {
    code: "mn",
    slug: "mongolia",
    name: "Mongolia",
    flag: "🇲🇳",
    region: "Asia",
    status: "draft",
  },
  {
    code: "me",
    slug: "montenegro",
    name: "Montenegro",
    flag: "🇲🇪",
    region: "Europe",
    status: "draft",
  },
  {
    code: "ma",
    slug: "morocco",
    name: "Morocco",
    flag: "🇲🇦",
    region: "Africa",
    status: "published",
  },
  {
    code: "mz",
    slug: "mozambique",
    name: "Mozambique",
    flag: "🇲🇿",
    region: "Africa",
    status: "draft",
  },
  {
    code: "mm",
    slug: "myanmar",
    name: "Myanmar",
    flag: "🇲🇲",
    region: "Asia",
    status: "draft",
  },
  {
    code: "na",
    slug: "namibia",
    name: "Namibia",
    flag: "🇳🇦",
    region: "Africa",
    status: "draft",
  },
  {
    code: "nr",
    slug: "nauru",
    name: "Nauru",
    flag: "🇳🇷",
    region: "Oceania",
    status: "draft",
  },
  {
    code: "np",
    slug: "nepal",
    name: "Nepal",
    flag: "🇳🇵",
    region: "Asia",
    status: "draft",
  },
  {
    code: "nl",
    slug: "netherlands",
    name: "Netherlands",
    flag: "🇳🇱",
    region: "Europe",
    status: "published",
  },
  {
    code: "nz",
    slug: "new-zealand",
    name: "New Zealand",
    flag: "🇳🇿",
    region: "Oceania",
    status: "draft",
  },
  {
    code: "ni",
    slug: "nicaragua",
    name: "Nicaragua",
    flag: "🇳🇮",
    region: "Americas",
    status: "draft",
  },
  {
    code: "ne",
    slug: "niger",
    name: "Niger",
    flag: "🇳🇪",
    region: "Africa",
    status: "draft",
  },
  {
    code: "ng",
    slug: "nigeria",
    name: "Nigeria",
    flag: "🇳🇬",
    region: "Africa",
    status: "draft",
  },
  {
    code: "mk",
    slug: "north-macedonia",
    name: "North Macedonia",
    flag: "🇲🇰",
    region: "Europe",
    status: "draft",
  },
  {
    code: "no",
    slug: "norway",
    name: "Norway",
    flag: "🇳🇴",
    region: "Europe",
    status: "draft",
  },
  { code: "om", slug: "oman", name: "Oman", flag: "🇴🇲", region: "Asia", status: "draft" },
  {
    code: "pk",
    slug: "pakistan",
    name: "Pakistan",
    flag: "🇵🇰",
    region: "Asia",
    status: "draft",
  },
  {
    code: "pw",
    slug: "palau",
    name: "Palau",
    flag: "🇵🇼",
    region: "Oceania",
    status: "draft",
  },
  {
    code: "ps",
    slug: "palestine",
    name: "Palestine",
    flag: "🇵🇸",
    region: "Asia",
    status: "draft",
  },
  {
    code: "pa",
    slug: "panama",
    name: "Panama",
    flag: "🇵🇦",
    region: "Americas",
    status: "draft",
  },
  {
    code: "pg",
    slug: "papua-new-guinea",
    name: "Papua New Guinea",
    flag: "🇵🇬",
    region: "Oceania",
    status: "draft",
  },
  {
    code: "py",
    slug: "paraguay",
    name: "Paraguay",
    flag: "🇵🇾",
    region: "Americas",
    status: "draft",
  },
  {
    code: "pe",
    slug: "peru",
    name: "Peru",
    flag: "🇵🇪",
    region: "Americas",
    status: "published",
  },
  {
    code: "ph",
    slug: "philippines",
    name: "Philippines",
    flag: "🇵🇭",
    region: "Asia",
    status: "draft",
  },
  {
    code: "pl",
    slug: "poland",
    name: "Poland",
    flag: "🇵🇱",
    region: "Europe",
    status: "draft",
  },
  {
    code: "pt",
    slug: "portugal",
    name: "Portugal",
    flag: "🇵🇹",
    region: "Europe",
    status: "draft",
  },
  {
    code: "qa",
    slug: "qatar",
    name: "Qatar",
    flag: "🇶🇦",
    region: "Asia",
    status: "draft",
  },
  {
    code: "ro",
    slug: "romania",
    name: "Romania",
    flag: "🇷🇴",
    region: "Europe",
    status: "draft",
  },
  {
    code: "ru",
    slug: "russia",
    name: "Russia",
    flag: "🇷🇺",
    region: "Europe",
    status: "draft",
  },
  {
    code: "rw",
    slug: "rwanda",
    name: "Rwanda",
    flag: "🇷🇼",
    region: "Africa",
    status: "draft",
  },
  {
    code: "kn",
    slug: "saint-kitts-and-nevis",
    name: "Saint Kitts and Nevis",
    flag: "🇰🇳",
    region: "Americas",
    status: "draft",
  },
  {
    code: "lc",
    slug: "saint-lucia",
    name: "Saint Lucia",
    flag: "🇱🇨",
    region: "Americas",
    status: "draft",
  },
  {
    code: "vc",
    slug: "saint-vincent",
    name: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    region: "Americas",
    status: "draft",
  },
  {
    code: "ws",
    slug: "samoa",
    name: "Samoa",
    flag: "🇼🇸",
    region: "Oceania",
    status: "draft",
  },
  {
    code: "sm",
    slug: "san-marino",
    name: "San Marino",
    flag: "🇸🇲",
    region: "Europe",
    status: "draft",
  },
  {
    code: "st",
    slug: "sao-tome-and-principe",
    name: "São Tomé and Príncipe",
    flag: "🇸🇹",
    region: "Africa",
    status: "draft",
  },
  {
    code: "sa",
    slug: "saudi-arabia",
    name: "Saudi Arabia",
    flag: "🇸🇦",
    region: "Asia",
    status: "draft",
  },
  {
    code: "sn",
    slug: "senegal",
    name: "Senegal",
    flag: "🇸🇳",
    region: "Africa",
    status: "published",
  },
  {
    code: "rs",
    slug: "serbia",
    name: "Serbia",
    flag: "🇷🇸",
    region: "Europe",
    status: "draft",
  },
  {
    code: "sc",
    slug: "seychelles",
    name: "Seychelles",
    flag: "🇸🇨",
    region: "Africa",
    status: "draft",
  },
  {
    code: "sl",
    slug: "sierra-leone",
    name: "Sierra Leone",
    flag: "🇸🇱",
    region: "Africa",
    status: "draft",
  },
  {
    code: "sg",
    slug: "singapore",
    name: "Singapore",
    flag: "🇸🇬",
    region: "Asia",
    status: "draft",
  },
  {
    code: "sk",
    slug: "slovakia",
    name: "Slovakia",
    flag: "🇸🇰",
    region: "Europe",
    status: "draft",
  },
  {
    code: "si",
    slug: "slovenia",
    name: "Slovenia",
    flag: "🇸🇮",
    region: "Europe",
    status: "draft",
  },
  {
    code: "sb",
    slug: "solomon-islands",
    name: "Solomon Islands",
    flag: "🇸🇧",
    region: "Oceania",
    status: "draft",
  },
  {
    code: "so",
    slug: "somalia",
    name: "Somalia",
    flag: "🇸🇴",
    region: "Africa",
    status: "draft",
  },
  {
    code: "za",
    slug: "south-africa",
    name: "South Africa",
    flag: "🇿🇦",
    region: "Africa",
    status: "published",
  },
  {
    code: "ss",
    slug: "south-sudan",
    name: "South Sudan",
    flag: "🇸🇸",
    region: "Africa",
    status: "draft",
  },
  {
    code: "es",
    slug: "spain",
    name: "Spain",
    flag: "🇪🇸",
    region: "Europe",
    status: "published",
  },
  {
    code: "lk",
    slug: "sri-lanka",
    name: "Sri Lanka",
    flag: "🇱🇰",
    region: "Asia",
    status: "draft",
  },
  {
    code: "sd",
    slug: "sudan",
    name: "Sudan",
    flag: "🇸🇩",
    region: "Africa",
    status: "draft",
  },
  {
    code: "sr",
    slug: "suriname",
    name: "Suriname",
    flag: "🇸🇷",
    region: "Americas",
    status: "draft",
  },
  {
    code: "se",
    slug: "sweden",
    name: "Sweden",
    flag: "🇸🇪",
    region: "Europe",
    status: "draft",
  },
  {
    code: "ch",
    slug: "switzerland",
    name: "Switzerland",
    flag: "🇨🇭",
    region: "Europe",
    status: "draft",
  },
  {
    code: "sy",
    slug: "syria",
    name: "Syria",
    flag: "🇸🇾",
    region: "Asia",
    status: "draft",
  },
  {
    code: "tw",
    slug: "taiwan",
    name: "Taiwan",
    flag: "🇹🇼",
    region: "Asia",
    status: "draft",
  },
  {
    code: "tj",
    slug: "tajikistan",
    name: "Tajikistan",
    flag: "🇹🇯",
    region: "Asia",
    status: "draft",
  },
  {
    code: "tz",
    slug: "tanzania",
    name: "Tanzania",
    flag: "🇹🇿",
    region: "Africa",
    status: "draft",
  },
  {
    code: "th",
    slug: "thailand",
    name: "Thailand",
    flag: "🇹🇭",
    region: "Asia",
    status: "draft",
  },
  {
    code: "tl",
    slug: "timor-leste",
    name: "Timor-Leste",
    flag: "🇹🇱",
    region: "Asia",
    status: "draft",
  },
  {
    code: "tg",
    slug: "togo",
    name: "Togo",
    flag: "🇹🇬",
    region: "Africa",
    status: "draft",
  },
  {
    code: "to",
    slug: "tonga",
    name: "Tonga",
    flag: "🇹🇴",
    region: "Oceania",
    status: "draft",
  },
  {
    code: "tt",
    slug: "trinidad-and-tobago",
    name: "Trinidad and Tobago",
    flag: "🇹🇹",
    region: "Americas",
    status: "draft",
  },
  {
    code: "tn",
    slug: "tunisia",
    name: "Tunisia",
    flag: "🇹🇳",
    region: "Africa",
    status: "draft",
  },
  {
    code: "tr",
    slug: "turkey",
    name: "Turkey",
    flag: "🇹🇷",
    region: "Asia",
    status: "published",
  },
  {
    code: "tm",
    slug: "turkmenistan",
    name: "Turkmenistan",
    flag: "🇹🇲",
    region: "Asia",
    status: "draft",
  },
  {
    code: "tv",
    slug: "tuvalu",
    name: "Tuvalu",
    flag: "🇹🇻",
    region: "Oceania",
    status: "draft",
  },
  {
    code: "ug",
    slug: "uganda",
    name: "Uganda",
    flag: "🇺🇬",
    region: "Africa",
    status: "draft",
  },
  {
    code: "ua",
    slug: "ukraine",
    name: "Ukraine",
    flag: "🇺🇦",
    region: "Europe",
    status: "draft",
  },
  {
    code: "ae",
    slug: "united-arab-emirates",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    region: "Asia",
    status: "draft",
  },
  {
    code: "gb",
    slug: "united-kingdom",
    name: "United Kingdom",
    flag: "🇬🇧",
    region: "Europe",
    status: "draft",
  },
  {
    code: "us",
    slug: "united-states",
    name: "United States",
    flag: "🇺🇸",
    region: "Americas",
    status: "draft",
  },
  {
    code: "uy",
    slug: "uruguay",
    name: "Uruguay",
    flag: "🇺🇾",
    region: "Americas",
    status: "draft",
  },
  {
    code: "uz",
    slug: "uzbekistan",
    name: "Uzbekistan",
    flag: "🇺🇿",
    region: "Asia",
    status: "draft",
  },
  {
    code: "vu",
    slug: "vanuatu",
    name: "Vanuatu",
    flag: "🇻🇺",
    region: "Oceania",
    status: "draft",
  },
  {
    code: "va",
    slug: "vatican-city",
    name: "Vatican City",
    flag: "🇻🇦",
    region: "Europe",
    status: "draft",
  },
  {
    code: "ve",
    slug: "venezuela",
    name: "Venezuela",
    flag: "🇻🇪",
    region: "Americas",
    status: "draft",
  },
  {
    code: "vn",
    slug: "vietnam",
    name: "Vietnam",
    flag: "🇻🇳",
    region: "Asia",
    status: "published",
  },
  {
    code: "ye",
    slug: "yemen",
    name: "Yemen",
    flag: "🇾🇪",
    region: "Asia",
    status: "draft",
  },
  {
    code: "zm",
    slug: "zambia",
    name: "Zambia",
    flag: "🇿🇲",
    region: "Africa",
    status: "draft",
  },
  {
    code: "zw",
    slug: "zimbabwe",
    name: "Zimbabwe",
    flag: "🇿🇼",
    region: "Africa",
    status: "draft",
  },
];

export const CATALOG_SIZE = countryCatalog.length;
