import type { AuthoredCountry } from "@/types/content";

export const egCountry: AuthoredCountry = {
  code: "eg",
  slug: "egypt",
  name: "Egypt",
  flag: "🇪🇬",
  region: "Africa",
  introduction: "Egyptian cooking makes everyday comfort from beans, lentils, rice, aromatic spices, fresh herbs, and bread, with street-food favourites sitting beside long-loved home dishes.",
  cuisineAliases: ["Egyptian restaurant", "Egyptisch restaurant", "Egyptian cuisine"],
  nationalDishId: "koshari",
  nationalDrink: {
    name: "Karkade",
    localName: "كركديه",
    type: "tea",
    alcoholic: false,
    description: "A ruby-red hibiscus infusion served chilled or warm with a tart, floral taste.",
  },
  menu: {
    starter: {
      id: "taameya",
      name: "Egyptian Fava Falafel",
      localName: "\u0637\u0639\u0645\u064a\u0629",
      description: "Green, herb-filled fava bean fritters with a crisp crust and tender fragrant centre.",
      category: "starter",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "dried fava beans", quantity: 400, unit: "g" },
        { name: "fresh herbs", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Soak beans overnight and drain them thoroughly.",
        "2. Blend with herbs, onion, and spices into a coarse paste.",
        "3. Shape and fry until crisp and deeply green inside.",
      ],
    },
    main: {
      id: "koshari",
      name: "Koshari",
      localName: "\u0643\u0634\u0631\u064a",
      description: "A widely considered Egyptian staple of lentils, rice, pasta, crisp onions, and spiced tomato sauce.",
      category: "main",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "brown lentils", quantity: 400, unit: "g" },
        { name: "rice", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Cook lentils and rice separately until tender.",
        "2. Make a sharp tomato sauce with garlic and vinegar.",
        "3. Layer grains, pasta, onions, and sauce in warm bowls.",
      ],
      substitutions: ['Use red lentils and a mild tomato passata from Dutch supermarkets for an accessible version.'],
    },
    side: {
      id: "salata-baladi",
      name: "Village Salad",
      localName: "\u0633\u0644\u0637\u0629 \u0628\u0644\u062f\u064a",
      description: "Tomato, cucumber, herbs, and lemon make a fresh and simple salad for rich dishes.",
      category: "side",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "tomatoes", quantity: 400, unit: "g" },
        { name: "cucumber", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Dice the vegetables into evenly sized small pieces.",
        "2. Dress with lemon juice, oil, and a pinch of salt.",
        "3. Scatter herbs over the salad immediately before serving.",
      ],
    },
    dessert: {
      id: "basbousa",
      name: "Semolina Syrup Cake",
      localName: "\u0628\u0633\u0628\u0648\u0633\u0629",
      description: "A tender semolina cake soaked in citrus syrup and topped with a single almond.",
      category: "dessert",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "semolina", quantity: 400, unit: "g" },
        { name: "yogurt", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Mix semolina with yogurt and melted butter gently.",
        "2. Bake until golden and springy at the centre.",
        "3. Pour cool citrus syrup over the warm cake.",
      ],
    },
    drink: {
      name: "Karkade",
      localName: "كركديه",
      type: "tea",
      alcoholic: false,
      description: "A ruby-red hibiscus infusion served chilled or warm with a tart, floral taste.",
    },
    moreRecipes: [
      {
        id: "ful-medames",
        name: "Ful Medames",
        localName: "فول مدمس",
        description:
          "Slow-cooked fava beans mashed with olive oil, lemon, cumin, and fresh herbs.",
        category: "main",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["vegetarian", "vegan"],
        ingredients: [
          { name: "dried fava beans", quantity: 300, unit: "g" },
          { name: "olive oil", quantity: 60, unit: "ml" },
          { name: "lemons", quantity: 2, unit: "pieces" },
          { name: "cumin", quantity: 5, unit: "g" },
        ],
        steps: [
          "1. Soak and simmer fava beans until very soft.",
          "2. Mash roughly with cumin, lemon, garlic, and olive oil.",
          "3. Serve warm with pita, eggs, and chopped tomato-onion salad.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Ful_medames",
      },
      {
        id: "molokhia",
        name: "Molokhia",
        localName: "ملوخية",
        description:
          "Silky jute-leaf soup fragrant with garlic and coriander, poured over rice.",
        category: "side",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["contains-meat"],
        ingredients: [
          { name: "frozen chopped molokhia", quantity: 400, unit: "g" },
          { name: "chicken stock", quantity: 800, unit: "ml" },
          { name: "garlic", quantity: 6, unit: "cloves" },
          { name: "coriander", quantity: 20, unit: "g" },
        ],
        steps: [
          "1. Bring stock to a simmer and stir in molokhia without boiling hard.",
          "2. Fry garlic and coriander in ghee or oil until golden.",
          "3. Stir the garlic mixture into the soup and serve over rice with chicken.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Mulukhiyah",
      },
      {
        id: "om-ali",
        name: "Om Ali",
        localName: "أم علي",
        description:
          "Egyptian bread pudding baked with milk, nuts, and coconut until bubbling.",
        category: "dessert",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["vegetarian"],
        ingredients: [
          { name: "puff pastry or stale croissants", quantity: 250, unit: "g" },
          { name: "milk", quantity: 800, unit: "ml" },
          { name: "mixed nuts", quantity: 100, unit: "g" },
          { name: "sugar", quantity: 80, unit: "g" },
        ],
        steps: [
          "1. Bake or toast pastry pieces until crisp, then break into a dish.",
          "2. Scatter nuts and raisins, then pour over sweetened hot milk.",
          "3. Bake until golden and bubbling on top; serve warm.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Om_Ali",
      },
    ],
  },
  status: "published",
};
