import type { AuthoredCountry, Recipe } from "@/types/content";
const r = (
  id: string,
  name: string,
  localName: string,
  description: string,
  category: Recipe["category"],
  ingredients: Recipe["ingredients"],
  steps: string[],
): Recipe => ({
  id,
  name,
  localName,
  description,
  category,
  servings: 4,
  prepMinutes: 20,
  cookMinutes: 30,
  difficulty: "medium",
  dietaryLabels: [],
  ingredients,
  steps,
});
export const esCountry: AuthoredCountry = {
  code: "es",
  slug: "spain",
  name: "Spain",
  flag: "🇪🇸",
  region: "Europe",
  introduction:
    "Spanish food rewards unhurried sharing, from bar snacks to rice cooked for a crowd. Olive oil, saffron, seafood, cured ham, and seasonal produce anchor its many regional traditions.",
  cuisineAliases: ["Spanish restaurant", "Spaans restaurant", "tapas restaurant"],
  nationalDishId: "paella-valenciana",
  nationalDrink: {
    name: "Rioja",
    type: "wine",
    alcoholic: true,
    description: "A well-known Spanish red wine with ripe fruit and gentle oak.",
  },
  menu: {
    starter: r(
      "patatas-bravas",
      "Patatas Bravas",
      "Patatas bravas",
      "Crisp potatoes with smoky tomato sauce and garlicky mayo.",
      "starter",
      [
        { name: "potatoes", quantity: 800, unit: "g" },
        { name: "tomato passata", quantity: 250, unit: "ml" },
        { name: "smoked paprika", quantity: 5, unit: "g" },
      ],
      [
        "1. Roast or fry potato cubes until crisp.",
        "2. Simmer passata with paprika and garlic.",
        "3. Spoon sauce over potatoes and add aioli.",
      ],
    ),
    main: r(
      "paella-valenciana",
      "Valencian Paella",
      "Paella valenciana",
      "Saffron rice with chicken, beans, and a prized toasted base.",
      "main",
      [
        { name: "paella rice", quantity: 400, unit: "g" },
        { name: "chicken thighs", quantity: 600, unit: "g" },
        { name: "green beans", quantity: 250, unit: "g" },
        { name: "saffron", quantity: 1, unit: "pinch" },
      ],
      [
        "1. Brown chicken in a broad pan, then add beans and tomato.",
        "2. Add stock, saffron, and rice; spread once and do not stir.",
        "3. Cook until tender with a lightly caramelized socarrat at the base.",
      ],
    ),
    side: r(
      "pan-con-tomate",
      "Tomato Bread",
      "Pan con tomate",
      "Garlic-rubbed toast slicked with ripe tomato and olive oil.",
      "side",
      [
        { name: "rustic bread", quantity: 8, unit: "slices" },
        { name: "ripe tomatoes", quantity: 3, unit: "pieces" },
        { name: "olive oil", quantity: 45, unit: "ml" },
      ],
      [
        "1. Toast bread.",
        "2. Rub with garlic and halved tomato.",
        "3. Finish with olive oil and flaky salt.",
      ],
    ),
    dessert: r(
      "crema-catalana",
      "Catalan Cream",
      "Crema catalana",
      "Citrus and cinnamon custard under a crackling sugar lid.",
      "dessert",
      [
        { name: "milk", quantity: 600, unit: "ml" },
        { name: "egg yolks", quantity: 6, unit: "pieces" },
        { name: "sugar", quantity: 120, unit: "g" },
        { name: "cornstarch", quantity: 25, unit: "g" },
      ],
      [
        "1. Infuse milk with lemon peel and cinnamon.",
        "2. Whisk yolks, sugar, and starch; cook with milk until thick.",
        "3. Chill, sugar the surface, and caramelize.",
      ],
    ),
    drink: {
      name: "Horchata",
      localName: "Horchata de chufa",
      type: "soft-drink",
      alcoholic: false,
      description: "A chilled, sweet tiger-nut drink from Valencia.",
    },
    moreRecipes: [
      r(
        "tortilla-espanola",
        "Spanish Potato Omelette",
        "Tortilla española",
        "Eggs and slowly cooked potatoes set into a thick omelette, served warm or room temperature.",
        "main",
        [
        { name: "waxy potatoes", quantity: 700, unit: "g" },
        { name: "eggs", quantity: 6, unit: "pieces" },
        { name: "onion", quantity: 1, unit: "piece" },
        { name: "olive oil", quantity: 120, unit: "ml" },
        ],
        [
        "1. Gently fry sliced potatoes and onion in olive oil until tender, then drain.",
        "2. Mix with beaten seasoned eggs and return to a hot pan.",
        "3. Cook until set, flip carefully, and finish the second side.",
        ],
      ),
      r(
        "gazpacho",
        "Andalusian Gazpacho",
        "Gazpacho",
        "Chilled tomato soup blended with pepper, cucumber, garlic, and olive oil.",
        "starter",
        [
        { name: "ripe tomatoes", quantity: 800, unit: "g" },
        { name: "cucumber", quantity: 0.5, unit: "piece" },
        { name: "green pepper", quantity: 1, unit: "piece" },
        { name: "stale bread", quantity: 60, unit: "g" },
        ],
        [
        "1. Soak bread briefly, then blend with tomatoes, cucumber, pepper, and garlic.",
        "2. Stream in olive oil and sherry vinegar until silky.",
        "3. Chill well and serve with diced vegetable garnishes.",
        ],
      ),
      r(
        "churros",
        "Churros with Chocolate",
        "Churros",
        "Crisp fried dough ridges rolled in sugar and dipped in thick drinking chocolate.",
        "dessert",
        [
        { name: "flour", quantity: 250, unit: "g" },
        { name: "water", quantity: 250, unit: "ml" },
        { name: "butter", quantity: 30, unit: "g" },
        { name: "dark chocolate", quantity: 150, unit: "g" },
        ],
        [
        "1. Bring water, butter, and salt to a boil, then beat in flour to a smooth dough.",
        "2. Pipe ridges into hot oil and fry until deep golden.",
        "3. Toss in sugar and serve with melted chocolate for dipping.",
        ],
      ),
    ],
  },
  status: "published",
};
