import type { AuthoredCountry, Recipe } from "@/types/content";
const r = (
  id: string,
  name: string,
  localName: string,
  description: string,
  category: Recipe["category"],
  ingredients: Recipe["ingredients"],
  steps: string[],
): Recipe => ({
  id,
  name,
  localName,
  description,
  category,
  servings: 4,
  prepMinutes: 20,
  cookMinutes: 30,
  difficulty: "medium",
  dietaryLabels: [],
  ingredients,
  steps,
});
export const esCountry: AuthoredCountry = {
  code: "es",
  slug: "spain",
  name: "Spain",
  flag: "🇪🇸",
  region: "Europe",
  introduction:
    "Spanish food rewards unhurried sharing, from bar snacks to rice cooked for a crowd. Olive oil, saffron, seafood, cured ham, and seasonal produce anchor its many regional traditions.",
  cuisineAliases: ["Spanish restaurant", "Spaans restaurant", "tapas restaurant"],
  nationalDishId: "paella-valenciana",
  nationalDrink: {
    name: "Rioja",
    type: "wine",
    alcoholic: true,
    description: "A well-known Spanish red wine with ripe fruit and gentle oak.",
  },
  menu: {
    starter: r(
      "patatas-bravas",
      "Patatas Bravas",
      "Patatas bravas",
      "Crisp potatoes with smoky tomato sauce and garlicky mayo.",
      "starter",
      [
        { name: "potatoes", quantity: 800, unit: "g" },
        { name: "tomato passata", quantity: 250, unit: "ml" },
        { name: "smoked paprika", quantity: 5, unit: "g" },
      ],
      [
        "1. Roast or fry potato cubes until crisp.",
        "2. Simmer passata with paprika and garlic.",
        "3. Spoon sauce over potatoes and add aioli.",
      ],
    ),
    main: r(
      "paella-valenciana",
      "Valencian Paella",
      "Paella valenciana",
      "Saffron rice with chicken, beans, and a prized toasted base.",
      "main",
      [
        { name: "paella rice", quantity: 400, unit: "g" },
        { name: "chicken thighs", quantity: 600, unit: "g" },
        { name: "green beans", quantity: 250, unit: "g" },
        { name: "saffron", quantity: 1, unit: "pinch" },
      ],
      [
        "1. Brown chicken in a broad pan, then add beans and tomato.",
        "2. Add stock, saffron, and rice; spread once and do not stir.",
        "3. Cook until tender with a lightly caramelized socarrat at the base.",
      ],
    ),
    side: r(
      "pan-con-tomate",
      "Tomato Bread",
      "Pan con tomate",
      "Garlic-rubbed toast slicked with ripe tomato and olive oil.",
      "side",
      [
        { name: "rustic bread", quantity: 8, unit: "slices" },
        { name: "ripe tomatoes", quantity: 3, unit: "pieces" },
        { name: "olive oil", quantity: 45, unit: "ml" },
      ],
      [
        "1. Toast bread.",
        "2. Rub with garlic and halved tomato.",
        "3. Finish with olive oil and flaky salt.",
      ],
    ),
    dessert: r(
      "crema-catalana",
      "Catalan Cream",
      "Crema catalana",
      "Citrus and cinnamon custard under a crackling sugar lid.",
      "dessert",
      [
        { name: "milk", quantity: 600, unit: "ml" },
        { name: "egg yolks", quantity: 6, unit: "pieces" },
        { name: "sugar", quantity: 120, unit: "g" },
        { name: "cornstarch", quantity: 25, unit: "g" },
      ],
      [
        "1. Infuse milk with lemon peel and cinnamon.",
        "2. Whisk yolks, sugar, and starch; cook with milk until thick.",
        "3. Chill, sugar the surface, and caramelize.",
      ],
    ),
    drink: {
      name: "Horchata",
      localName: "Horchata de chufa",
      type: "soft-drink",
      alcoholic: false,
      description: "A chilled, sweet tiger-nut drink from Valencia.",
    },
  },
  status: "published",
};
