import type { AuthoredCountry } from "@/types/content";

export const frCountry: AuthoredCountry = {
  code: "fr",
  slug: "france",
  name: "France",
  flag: "🇫🇷",
  region: "Europe",
  introduction: "French cooking celebrates regional produce through careful technique, from market vegetables and rustic braises to pastries that turn simple ingredients into memorable meals.",
  cuisineAliases: ["French restaurant", "Frans restaurant", "Franse keuken"],
  nationalDishId: "boeuf-bourguignon",
  nationalDrink: {
    name: "French Wine",
    localName: "Vin français",
    type: "wine",
    alcoholic: true,
    description: "A regional glass of wine is a natural companion to a long French dinner.",
  },
  menu: {
    starter: {
      id: "onion-soup",
      name: "French Onion Soup",
      localName: "Soupe \u00e0 l\u2019oignon",
      description: "Sweet onions slowly caramelised in stock beneath a toasted, bubbling cheese crust.",
      category: "starter",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "onions", quantity: 400, unit: "g" },
        { name: "Gruy\u00e8re", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Cook the onions slowly until deeply amber and sweet.",
        "2. Stir in flour and stock, then simmer until rounded.",
        "3. Top with bread and cheese, then grill until blistered.",
      ],
    },
    main: {
      id: "boeuf-bourguignon",
      name: "Burgundy Beef Stew",
      localName: "Boeuf bourguignon",
      description: "Beef is gently braised with red wine, mushrooms, and aromatic vegetables until spoon-tender.",
      category: "main",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["gluten-free"],
      ingredients: [
        { name: "beef chuck", quantity: 400, unit: "g" },
        { name: "red wine", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Brown the beef in batches to build a rich base.",
        "2. Simmer with wine and vegetables until the meat softens.",
        "3. Add mushrooms near the end and season before serving.",
      ],
      substitutions: ['Use Dutch runderlappen for beef chuck and a dry red wine such as Côtes du Rhône.'],
    },
    side: {
      id: "ratatouille",
      name: "Proven\u00e7al Vegetable Stew",
      localName: "Ratatouille",
      description: "Summer vegetables cooked gently in olive oil make a fragrant and colourful Proven\u00e7al side.",
      category: "side",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "aubergine", quantity: 400, unit: "g" },
        { name: "tomatoes", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Soften the vegetables separately to keep their character.",
        "2. Combine them with herbs and a splash of olive oil.",
        "3. Cook gently until tender but not collapsed.",
      ],
    },
    dessert: {
      id: "cr\u00e8me-br\u00fbl\u00e9e",
      name: "Vanilla Cr\u00e8me Br\u00fbl\u00e9e",
      localName: "Cr\u00e8me br\u00fbl\u00e9e",
      description: "Silky vanilla custard with a thin caramel lid that cracks beneath a spoon.",
      category: "dessert",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "double cream", quantity: 400, unit: "g" },
        { name: "egg yolks", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Warm the cream with vanilla until aromatic.",
        "2. Whisk yolks with sugar, then temper with the cream.",
        "3. Bake gently, chill well, and caramelise the top.",
      ],
    },
    drink: {
      name: "French Wine",
      localName: "Vin français",
      type: "wine",
      alcoholic: true,
      description: "A regional glass of wine is a natural companion to a long French dinner.",
    },
    moreRecipes: [
      {
        id: "quiche-lorraine",
        name: "Quiche Lorraine",
        localName: "Quiche lorraine",
        description:
          "Savoury custard tart with smoked bacon baked in a crisp pastry shell.",
        category: "main",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["contains-meat"],
        ingredients: [
          { name: "shortcrust pastry", quantity: 300, unit: "g" },
          { name: "smoked bacon lardons", quantity: 200, unit: "g" },
          { name: "eggs", quantity: 3, unit: "pieces" },
          { name: "cream", quantity: 250, unit: "ml" },
        ],
        steps: [
          "1. Blind-bake the pastry case until lightly coloured.",
          "2. Scatter fried lardons, then pour over beaten eggs and cream.",
          "3. Bake until just set in the centre with a golden top.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Quiche_Lorraine",
      },
      {
        id: "salade-nicoise",
        name: "Salade Niçoise",
        localName: "Salade niçoise",
        description:
          "Provençal composed salad of tuna, eggs, olives, tomatoes, and crisp vegetables.",
        category: "starter",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["gluten-free"],
        ingredients: [
          { name: "tuna in olive oil", quantity: 200, unit: "g" },
          { name: "eggs", quantity: 4, unit: "pieces" },
          { name: "tomatoes", quantity: 4, unit: "pieces" },
          { name: "Niçoise olives", quantity: 80, unit: "g" },
        ],
        steps: [
          "1. Soft-boil eggs and prepare tomatoes, beans, and potatoes if using.",
          "2. Arrange tuna, eggs, olives, and vegetables on a platter.",
          "3. Dress with olive oil, vinegar, and herbs at the table.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Salade_niçoise",
      },
      {
        id: "clafoutis",
        name: "Cherry Clafoutis",
        localName: "Clafoutis",
        description:
          "Batter pudding of cherries baked under a lightly sweet eggy custard.",
        category: "dessert",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["vegetarian"],
        ingredients: [
          { name: "cherries", quantity: 500, unit: "g" },
          { name: "eggs", quantity: 3, unit: "pieces" },
          { name: "milk", quantity: 250, unit: "ml" },
          { name: "flour", quantity: 80, unit: "g" },
        ],
        steps: [
          "1. Butter a dish and fill with pitted or whole cherries.",
          "2. Whisk eggs, sugar, flour, and milk into a thin batter.",
          "3. Pour over and bake until puffed and golden; dust with sugar.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Clafoutis",
      },
    ],
  },
  status: "published",
};
