import type { AuthoredCountry } from "@/types/content";

export const frCountry: AuthoredCountry = {
  code: "fr",
  slug: "france",
  name: "France",
  flag: "🇫🇷",
  region: "Europe",
  introduction: "French cooking celebrates regional produce through careful technique, from market vegetables and rustic braises to pastries that turn simple ingredients into memorable meals.",
  cuisineAliases: ["French restaurant", "Frans restaurant", "Franse keuken"],
  nationalDishId: "boeuf-bourguignon",
  nationalDrink: {
    name: "French Wine",
    localName: "Vin français",
    type: "wine",
    alcoholic: true,
    description: "A regional glass of wine is a natural companion to a long French dinner.",
  },
  menu: {
    starter: {
      id: "onion-soup",
      name: "French Onion Soup",
      localName: "Soupe \u00e0 l\u2019oignon",
      description: "Sweet onions slowly caramelised in stock beneath a toasted, bubbling cheese crust.",
      category: "starter",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "onions", quantity: 400, unit: "g" },
        { name: "Gruy\u00e8re", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Cook the onions slowly until deeply amber and sweet.",
        "2. Stir in flour and stock, then simmer until rounded.",
        "3. Top with bread and cheese, then grill until blistered.",
      ],
    },
    main: {
      id: "boeuf-bourguignon",
      name: "Burgundy Beef Stew",
      localName: "Boeuf bourguignon",
      description: "Beef is gently braised with red wine, mushrooms, and aromatic vegetables until spoon-tender.",
      category: "main",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["gluten-free"],
      ingredients: [
        { name: "beef chuck", quantity: 400, unit: "g" },
        { name: "red wine", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Brown the beef in batches to build a rich base.",
        "2. Simmer with wine and vegetables until the meat softens.",
        "3. Add mushrooms near the end and season before serving.",
      ],
      substitutions: ['Use Dutch runderlappen for beef chuck and a dry red wine such as Côtes du Rhône.'],
    },
    side: {
      id: "ratatouille",
      name: "Proven\u00e7al Vegetable Stew",
      localName: "Ratatouille",
      description: "Summer vegetables cooked gently in olive oil make a fragrant and colourful Proven\u00e7al side.",
      category: "side",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "aubergine", quantity: 400, unit: "g" },
        { name: "tomatoes", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Soften the vegetables separately to keep their character.",
        "2. Combine them with herbs and a splash of olive oil.",
        "3. Cook gently until tender but not collapsed.",
      ],
    },
    dessert: {
      id: "cr\u00e8me-br\u00fbl\u00e9e",
      name: "Vanilla Cr\u00e8me Br\u00fbl\u00e9e",
      localName: "Cr\u00e8me br\u00fbl\u00e9e",
      description: "Silky vanilla custard with a thin caramel lid that cracks beneath a spoon.",
      category: "dessert",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "double cream", quantity: 400, unit: "g" },
        { name: "egg yolks", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Warm the cream with vanilla until aromatic.",
        "2. Whisk yolks with sugar, then temper with the cream.",
        "3. Bake gently, chill well, and caramelise the top.",
      ],
    },
    drink: {
      name: "French Wine",
      localName: "Vin français",
      type: "wine",
      alcoholic: true,
      description: "A regional glass of wine is a natural companion to a long French dinner.",
    },
  },
  status: "published",
};
