import type { Country } from "@/types/content";
import { drink } from "./content-helpers";

export const geCountry: Country = {
  code: "ge",
  slug: "georgia",
  name: "Georgia",
  flag: "🇬🇪",
  region: "Asia/Europe (Caucasus)",
  introduction:
    "Georgian cooking is built for generous shared tables, with herbs, walnuts, cheese, and sour fruit appearing often. Bread and dumplings make its feast culture especially memorable.",
  cuisineAliases: [
    "Georgian restaurant",
    "restaurant uit Georgië",
    "Kaukasisch restaurant",
  ],
  nationalDishId: "khachapuri-adjaruli",
  nationalDrink: drink(
    "Qvevri Wine",
    "ქვევრის ღვინო",
    "wine",
    true,
    "Georgian wine traditionally fermented in large clay vessels.",
  ),
  menu: {
    starter: {
      id: "pkhali",
      name: "Spinach Pkhali",
      localName: "ფხალი",
      description: "Herby spinach and walnut bites with a gentle garlic kick.",
      category: "starter",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 5,
      difficulty: "easy",
      dietaryLabels: ["vegetarian", "vegan"],
      ingredients: [
        { name: "spinach", quantity: 400, unit: "g" },
        { name: "walnuts", quantity: 120, unit: "g" },
        { name: "garlic", quantity: 2, unit: "cloves" },
        { name: "coriander", quantity: 20, unit: "g" },
      ],
      steps: [
        "1. Blanch spinach, squeeze it very dry, and chop.",
        "2. Grind walnuts, garlic, coriander, salt, and a splash of vinegar.",
        "3. Mix, form small mounds, and chill before serving.",
      ],
    },
    main: {
      id: "khachapuri-adjaruli",
      name: "Adjarian Khachapuri",
      localName: "აჭარული ხაჭაპური",
      description: "Boat-shaped bread filled with molten cheese and finished with egg.",
      category: "main",
      servings: 4,
      prepMinutes: 35,
      cookMinutes: 18,
      difficulty: "challenging",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "bread flour", quantity: 500, unit: "g" },
        { name: "yeast", quantity: 7, unit: "g" },
        { name: "mozzarella", quantity: 300, unit: "g" },
        { name: "feta", quantity: 200, unit: "g" },
        { name: "eggs", quantity: 4, unit: "pieces" },
      ],
      steps: [
        "1. Make a soft yeast dough, rise until doubled, then divide into four.",
        "2. Shape each into a boat and fill with mixed grated cheeses.",
        "3. Bake at 240°C until browned; add an egg for the final 2 minutes and stir in butter at the table.",
      ],
      substitutions: [
        "Mozzarella plus feta is a Dutch-supermarket-friendly stand-in for Georgian sulguni.",
      ],
      drinkPairing: "Pair with dry amber qvevri wine.",
    },
    side: {
      id: "lobio",
      name: "Bean Stew",
      localName: "ლობიო",
      description: "Tender red beans seasoned with coriander and walnuts.",
      category: "side",
      servings: 4,
      prepMinutes: 15,
      cookMinutes: 35,
      difficulty: "easy",
      dietaryLabels: ["vegetarian", "vegan"],
      ingredients: [
        { name: "cooked kidney beans", quantity: 800, unit: "g" },
        { name: "onion", quantity: 1, unit: "piece" },
        { name: "walnuts", quantity: 60, unit: "g" },
        { name: "coriander", quantity: 20, unit: "g" },
      ],
      steps: [
        "1. Soften onion in oil with a pinch of ground coriander.",
        "2. Add beans and a splash of water; crush some beans for body.",
        "3. Fold in walnuts and fresh coriander just before serving.",
      ],
    },
    dessert: {
      id: "churchkhela",
      name: "Grape and Walnut Strings",
      localName: "ჩურჩხელა",
      description: "Walnuts coated in a chewy grape-thickened shell.",
      category: "dessert",
      servings: 8,
      prepMinutes: 25,
      cookMinutes: 25,
      difficulty: "medium",
      dietaryLabels: ["vegetarian", "vegan"],
      ingredients: [
        { name: "walnuts", quantity: 300, unit: "g" },
        { name: "grape juice", quantity: 750, unit: "ml" },
        { name: "flour", quantity: 80, unit: "g" },
        { name: "sugar", quantity: 40, unit: "g" },
      ],
      steps: [
        "1. Thread walnut halves onto eight sturdy strings.",
        "2. Whisk flour into cold grape juice, then simmer with sugar until glossy and thick.",
        "3. Dip strings twice, allowing them to set between coats.",
      ],
    },
    drink: drink(
      "Tarragon Lemonade",
      "Тархун",
      "soft-drink",
      false,
      "A bright green, anise-scented Georgian soft drink.",
    ),
    moreRecipes: [
      {
        id: "khinkali",
        name: "Khinkali Dumplings",
        localName: "ხინკალი",
        description:
          "Pleated soup dumplings filled with seasoned meat and eaten by hand.",
        category: "main",
        servings: 4,
        prepMinutes: 45,
        cookMinutes: 20,
        difficulty: "challenging",
        dietaryLabels: ["contains-meat"],
        ingredients: [
          { name: "flour", quantity: 500, unit: "g" },
          { name: "minced beef and pork", quantity: 500, unit: "g" },
          { name: "onion", quantity: 1, unit: "piece" },
          { name: "coriander", quantity: 15, unit: "g" },
        ],
        steps: [
          "1. Mix a firm dough and rest while preparing the filling.",
          "2. Combine minced meat with grated onion, herbs, salt, and pepper.",
          "3. Wrap into gathered dumplings and boil until the wrappers are tender.",
        ],
      },
      {
        id: "badrijani",
        name: "Walnut-Stuffed Eggplant",
        localName: "ბადრიჯანი ნიგვზით",
        description:
          "Fried eggplant rolls filled with a garlicky walnut paste for sharing plates.",
        category: "starter",
        servings: 4,
        prepMinutes: 25,
        cookMinutes: 20,
        difficulty: "medium",
        dietaryLabels: ["vegetarian", "vegan"],
        ingredients: [
          { name: "eggplants", quantity: 3, unit: "pieces" },
          { name: "walnuts", quantity: 200, unit: "g" },
          { name: "garlic", quantity: 3, unit: "cloves" },
          { name: "coriander", quantity: 20, unit: "g" },
        ],
        steps: [
          "1. Slice eggplants lengthwise and fry until soft and golden.",
          "2. Grind walnuts with garlic, coriander, and a splash of vinegar.",
          "3. Spread the paste, roll, and garnish with pomegranate seeds if available.",
        ],
      },
      {
        id: "ajapsandali",
        name: "Vegetable Stew",
        localName: "აჯაფსანდალი",
        description:
          "A summery stew of eggplant, peppers, tomatoes, and herbs cooked until jammy.",
        category: "side",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 40,
        difficulty: "easy",
        dietaryLabels: ["vegetarian", "vegan"],
        ingredients: [
          { name: "eggplant", quantity: 400, unit: "g" },
          { name: "bell peppers", quantity: 300, unit: "g" },
          { name: "tomatoes", quantity: 400, unit: "g" },
          { name: "onion", quantity: 2, unit: "pieces" },
        ],
        steps: [
          "1. Soften onion, then add diced eggplant and peppers.",
          "2. Stir in tomatoes and simmer until thick and glossy.",
          "3. Finish with fresh herbs and serve warm or at room temperature.",
        ],
      },
    ],
    moreDrinks: [
      drink(
        "Saperavi",
        "საფერავი",
        "wine",
        true,
        "Deep Georgian red wine that stands up to rich walnut and meat dishes.",
      ),
      drink(
        "Natakhtari Beer",
        "ნათახტარი",
        "beer",
        true,
        "Popular Georgian lager for casual supra-style sharing meals.",
      ),
      drink(
        "Borjomi",
        "ბორჯომი",
        "soft-drink",
        false,
        "Naturally sparkling mineral water often served with feasts.",
      ),
    ],
  },
  status: "published",
};
