import type { Country } from "@/types/content";

export const geCountry: Country = {
  code: "ge",
  slug: "georgia",
  name: "Georgia",
  flag: "🇬🇪",
  region: "Asia/Europe (Caucasus)",
  introduction:
    "Georgian cooking is built for generous shared tables, with herbs, walnuts, cheese, and sour fruit appearing often. Bread and dumplings make its feast culture especially memorable.",
  cuisineAliases: [
    "Georgian restaurant",
    "restaurant uit Georgië",
    "Kaukasisch restaurant",
  ],
  nationalDishId: "khachapuri-adjaruli",
  nationalDrink: {
    name: "Qvevri Wine",
    localName: "ქვევრის ღვინო",
    type: "wine",
    alcoholic: true,
    description: "Georgian wine traditionally fermented in large clay vessels.",
  },
  menu: {
    starter: {
      id: "pkhali",
      name: "Spinach Pkhali",
      localName: "ფხალი",
      description: "Herby spinach and walnut bites with a gentle garlic kick.",
      category: "starter",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 5,
      difficulty: "easy",
      dietaryLabels: ["vegan", "gluten-free"],
      ingredients: [
        { name: "spinach", quantity: 400, unit: "g" },
        { name: "walnuts", quantity: 120, unit: "g" },
        { name: "garlic", quantity: 2, unit: "cloves" },
        { name: "coriander", quantity: 20, unit: "g" },
      ],
      steps: [
        "1. Blanch spinach, squeeze it very dry, and chop.",
        "2. Grind walnuts, garlic, coriander, salt, and a splash of vinegar.",
        "3. Mix, form small mounds, and chill before serving.",
      ],
    },
    main: {
      id: "khachapuri-adjaruli",
      name: "Adjarian Khachapuri",
      localName: "აჭარული ხაჭაპური",
      description: "Boat-shaped bread filled with molten cheese and finished with egg.",
      category: "main",
      servings: 4,
      prepMinutes: 35,
      cookMinutes: 18,
      difficulty: "challenging",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "bread flour", quantity: 500, unit: "g" },
        { name: "yeast", quantity: 7, unit: "g" },
        { name: "mozzarella", quantity: 300, unit: "g" },
        { name: "feta", quantity: 200, unit: "g" },
        { name: "eggs", quantity: 4, unit: "pieces" },
      ],
      steps: [
        "1. Make a soft yeast dough, rise until doubled, then divide into four.",
        "2. Shape each into a boat and fill with mixed grated cheeses.",
        "3. Bake at 240°C until browned; add an egg for the final 2 minutes and stir in butter at the table.",
      ],
      substitutions: [
        "Mozzarella plus feta is a Dutch-supermarket-friendly stand-in for Georgian sulguni.",
      ],
      drinkPairing: "Pair with dry amber qvevri wine.",
    },
    side: {
      id: "lobio",
      name: "Bean Stew",
      localName: "ლობიო",
      description: "Tender red beans seasoned with coriander and walnuts.",
      category: "side",
      servings: 4,
      prepMinutes: 15,
      cookMinutes: 35,
      difficulty: "easy",
      dietaryLabels: ["vegan", "gluten-free"],
      ingredients: [
        { name: "cooked kidney beans", quantity: 800, unit: "g" },
        { name: "onion", quantity: 1, unit: "piece" },
        { name: "walnuts", quantity: 60, unit: "g" },
        { name: "coriander", quantity: 20, unit: "g" },
      ],
      steps: [
        "1. Soften onion in oil with a pinch of ground coriander.",
        "2. Add beans and a splash of water; crush some beans for body.",
        "3. Fold in walnuts and fresh coriander just before serving.",
      ],
    },
    dessert: {
      id: "churchkhela",
      name: "Grape and Walnut Strings",
      localName: "ჩურჩხელა",
      description: "Walnuts coated in a chewy grape-thickened shell.",
      category: "dessert",
      servings: 8,
      prepMinutes: 25,
      cookMinutes: 25,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "walnuts", quantity: 300, unit: "g" },
        { name: "grape juice", quantity: 750, unit: "ml" },
        { name: "flour", quantity: 80, unit: "g" },
        { name: "sugar", quantity: 40, unit: "g" },
      ],
      steps: [
        "1. Thread walnut halves onto eight sturdy strings.",
        "2. Whisk flour into cold grape juice, then simmer with sugar until glossy and thick.",
        "3. Dip strings twice, allowing them to set between coats.",
      ],
    },
    drink: {
      name: "Tarragon Lemonade",
      localName: "Тархун",
      type: "soft-drink",
      alcoholic: false,
      description: "A bright green, anise-scented Georgian soft drink.",
    },
  },
  status: "published",
};
