import type { AuthoredCountry, Recipe } from "@/types/content";
const r = (
  id: string,
  name: string,
  localName: string,
  description: string,
  category: Recipe["category"],
  ingredients: Recipe["ingredients"],
  steps: string[],
): Recipe => ({
  id,
  name,
  localName,
  description,
  category,
  servings: 4,
  prepMinutes: 20,
  cookMinutes: 30,
  difficulty: "medium",
  dietaryLabels: [],
  ingredients,
  steps,
});
export const grCountry: AuthoredCountry = {
  code: "gr",
  slug: "greece",
  name: "Greece",
  flag: "🇬🇷",
  region: "Europe",
  introduction:
    "Greek cooking puts sun-ripened vegetables, olive oil, herbs, lemon, and cheese at the centre. Meals are designed for passing around a table with bread and conversation.",
  cuisineAliases: ["Greek restaurant", "Grieks restaurant", "taverna"],
  nationalDishId: "moussaka",
  nationalDrink: {
    name: "Ouzo",
    type: "spirit",
    alcoholic: true,
    description: "An anise spirit that turns milky with water and suits meze.",
  },
  menu: {
    starter: r(
      "tzatziki",
      "Tzatziki",
      "Τζατζίκι",
      "Cool cucumber-yogurt dip with garlic and dill.",
      "starter",
      [
        { name: "Greek yogurt", quantity: 400, unit: "g" },
        { name: "cucumber", quantity: 1, unit: "piece" },
        { name: "garlic", quantity: 2, unit: "cloves" },
        { name: "dill", quantity: 15, unit: "g" },
      ],
      [
        "1. Grate cucumber, salt it, and squeeze dry.",
        "2. Mix with yogurt, garlic, dill, and olive oil.",
        "3. Chill before serving.",
      ],
    ),
    main: r(
      "moussaka",
      "Moussaka",
      "Μουσακάς",
      "Layers of aubergine, spiced lamb sauce, potato, and béchamel.",
      "main",
      [
        { name: "aubergines", quantity: 800, unit: "g" },
        { name: "ground lamb", quantity: 500, unit: "g" },
        { name: "potatoes", quantity: 500, unit: "g" },
        { name: "béchamel sauce", quantity: 500, unit: "ml" },
      ],
      [
        "1. Roast sliced aubergine and potatoes until tender.",
        "2. Simmer lamb with onion, tomato, cinnamon, and oregano.",
        "3. Layer vegetables and sauce, cover with béchamel, and bake until browned.",
      ],
    ),
    side: r(
      "horiatiki",
      "Village Salad",
      "Χωριάτικη σαλάτα",
      "Tomatoes, cucumber, olives, and feta in a simple olive-oil dressing.",
      "side",
      [
        { name: "tomatoes", quantity: 500, unit: "g" },
        { name: "cucumber", quantity: 1, unit: "piece" },
        { name: "feta", quantity: 200, unit: "g" },
        { name: "Kalamata olives", quantity: 100, unit: "g" },
      ],
      [
        "1. Chunk the vegetables.",
        "2. Add olives and oregano.",
        "3. Top with feta and olive oil.",
      ],
    ),
    dessert: r(
      "galaktoboureko",
      "Semolina Custard Pastry",
      "Γαλακτομπούρεκο",
      "Crisp filo surrounds fragrant semolina custard and syrup.",
      "dessert",
      [
        { name: "filo pastry", quantity: 250, unit: "g" },
        { name: "milk", quantity: 750, unit: "ml" },
        { name: "semolina", quantity: 120, unit: "g" },
        { name: "sugar", quantity: 180, unit: "g" },
      ],
      [
        "1. Cook milk and semolina into a thick custard.",
        "2. Enclose in buttered filo and bake at 180°C.",
        "3. Pour cool citrus syrup over hot pastry.",
      ],
    ),
    drink: {
      name: "Greek Coffee",
      type: "coffee",
      alcoholic: false,
      description: "Finely ground coffee brewed unfiltered in a small briki.",
    },
    moreRecipes: [
      r(
        "spanakopita",
        "Spinach Pie",
        "Σπανακόπιτα",
        "Flaky filo pastry layered with spinach, herbs, and briny feta cheese.",
        "starter",
        [
        { name: "filo pastry", quantity: 250, unit: "g" },
        { name: "spinach", quantity: 500, unit: "g" },
        { name: "feta", quantity: 200, unit: "g" },
        { name: "spring onions", quantity: 4, unit: "pieces" },
        ],
        [
        "1. Wilt spinach, squeeze dry, and mix with feta, herbs, and spring onions.",
        "2. Layer buttered filo in a tin, add filling, and top with more sheets.",
        "3. Score and bake until the pastry is shatteringly crisp.",
        ],
      ),
      r(
        "souvlaki",
        "Pork Souvlaki",
        "Σουβλάκι",
        "Lemon-oregano marinated pork skewers grilled until juicy and lightly charred.",
        "main",
        [
        { name: "pork shoulder", quantity: 700, unit: "g" },
        { name: "lemon", quantity: 2, unit: "pieces" },
        { name: "dried oregano", quantity: 10, unit: "g" },
        { name: "olive oil", quantity: 60, unit: "ml" },
        ],
        [
        "1. Cube the pork and marinate with lemon, oregano, garlic, and oil.",
        "2. Thread onto skewers and grill over high heat, turning often.",
        "3. Rest briefly and serve with pita, tzatziki, and salad.",
        ],
      ),
      r(
        "baklava",
        "Honey Nut Baklava",
        "Μπακλαβάς",
        "Buttery filo layers filled with nuts and soaked in fragrant honey syrup.",
        "dessert",
        [
        { name: "filo pastry", quantity: 250, unit: "g" },
        { name: "walnuts", quantity: 250, unit: "g" },
        { name: "butter", quantity: 150, unit: "g" },
        { name: "honey", quantity: 200, unit: "g" },
        ],
        [
        "1. Layer buttered filo with chopped nuts and cinnamon in a tin.",
        "2. Bake until golden, then pour cool honey syrup over the hot pastry.",
        "3. Rest until the syrup is absorbed before cutting into diamonds.",
        ],
      ),
    ],
  },
  status: "published",
};
