import type { Country, Recipe } from "@/types/content";
import { drink } from "./content-helpers";
const r = (
  id: string,
  name: string,
  localName: string,
  description: string,
  category: Recipe["category"],
  ingredients: Recipe["ingredients"],
  steps: string[],
  dietaryLabels: string[] = [],
  substitutions?: string[],
): Recipe => ({
  id,
  name,
  localName,
  description,
  category,
  servings: 4,
  prepMinutes: 20,
  cookMinutes: 25,
  difficulty: "medium",
  dietaryLabels,
  ingredients,
  steps,
  substitutions,
});
export const itCountry: Country = {
  code: "it",
  slug: "italy",
  name: "Italy",
  flag: "🇮🇹",
  region: "Europe",
  introduction:
    "Italian cooking is regional, seasonal, and proud of excellent few-ingredient dishes. Pasta, olive oil, tomatoes, cheese, and ritual coffee shape many everyday meals.",
  cuisineAliases: ["Italian restaurant", "Italiaans restaurant", "trattoria"],
  nationalDishId: "spaghetti-carbonara",
  nationalDrink: drink(
    "Italian Wine",
    "Vino",
    "wine",
    true,
    "Regional wines, from crisp whites to structured reds, are central at the table.",
  ),
  menu: {
    starter: r(
      "bruschetta",
      "Tomato Bruschetta",
      "Bruschetta al pomodoro",
      "Grilled bread rubbed with garlic and topped with juicy tomatoes.",
      "starter",
      [
        { name: "ciabatta", quantity: 8, unit: "slices" },
        { name: "tomatoes", quantity: 400, unit: "g" },
        { name: "basil", quantity: 15, unit: "g" },
      ],
      [
        "1. Toast bread and rub each slice with garlic.",
        "2. Dice tomatoes and dress with olive oil, salt, and basil.",
        "3. Spoon over bread immediately.",
      ],
      ["vegetarian", "vegan"],
    ),
    main: r(
      "spaghetti-carbonara",
      "Spaghetti Carbonara",
      "Spaghetti alla carbonara",
      "Silky Roman pasta made with egg, pecorino, pepper, and cured pork.",
      "main",
      [
        { name: "spaghetti", quantity: 400, unit: "g" },
        { name: "guanciale", quantity: 180, unit: "g" },
        { name: "eggs", quantity: 4, unit: "pieces" },
        { name: "pecorino romano", quantity: 100, unit: "g" },
      ],
      [
        "1. Render diced guanciale until crisp.",
        "2. Whisk eggs, cheese, and abundant black pepper.",
        "3. Toss hot pasta off heat with pork and egg mixture, loosening with pasta water.",
      ],
      ["contains-meat"],
      ["Pancetta is the closest easy Dutch substitute for guanciale."],
    ),
    side: r(
      "insalata-rucola",
      "Rocket Salad",
      "Insalata di rucola",
      "Peppery rocket leaves dressed with lemon, olive oil, and shaved Parmesan.",
      "side",
      [
        { name: "rocket", quantity: 120, unit: "g" },
        { name: "Parmesan", quantity: 60, unit: "g" },
        { name: "lemon", quantity: 1, unit: "piece" },
      ],
      [
        "1. Wash and dry rocket.",
        "2. Dress lightly with olive oil and lemon.",
        "3. Shave Parmesan over just before serving.",
      ],
      ["vegetarian"],
    ),
    dessert: r(
      "tiramisu",
      "Tiramisu",
      "Tiramisù",
      "Coffee-soaked biscuits layered with mascarpone cream.",
      "dessert",
      [
        { name: "mascarpone", quantity: 500, unit: "g" },
        { name: "eggs", quantity: 4, unit: "pieces" },
        { name: "ladyfingers", quantity: 250, unit: "g" },
        { name: "espresso", quantity: 250, unit: "ml" },
      ],
      [
        "1. Whisk yolks with sugar, then fold into mascarpone.",
        "2. Briefly dip biscuits in cooled espresso and layer with cream.",
        "3. Chill four hours and dust with cocoa.",
      ],
      ["vegetarian"],
    ),
    drink: drink(
      "Espresso",
      "Espresso",
      "coffee",
      false,
      "A short, intense coffee commonly enjoyed after a meal.",
    ),
    moreRecipes: [
      r(
        "caprese",
        "Caprese Salad",
        "Insalata Caprese",
        "Ripe tomatoes, mozzarella, and basil dressed simply with olive oil.",
        "starter",
        [
          { name: "tomatoes", quantity: 400, unit: "g" },
          { name: "mozzarella", quantity: 250, unit: "g" },
          { name: "basil", quantity: 20, unit: "g" },
        ],
        [
          "1. Slice tomatoes and mozzarella into even rounds.",
          "2. Arrange alternately with basil leaves.",
          "3. Drizzle with olive oil and season lightly with salt.",
        ],
        ["vegetarian"],
      ),
      r(
        "risotto-milanese",
        "Saffron Risotto",
        "Risotto alla milanese",
        "Creamy risotto tinted gold with saffron and finished with butter and cheese.",
        "main",
        [
          { name: "arborio rice", quantity: 320, unit: "g" },
          { name: "saffron", quantity: 0.5, unit: "g" },
          { name: "onion", quantity: 1, unit: "piece" },
          { name: "Parmesan", quantity: 80, unit: "g" },
        ],
        [
          "1. Soften onion in butter, then toast the rice.",
          "2. Add warm stock ladle by ladle with saffron infused in some of it.",
          "3. Finish off heat with butter and Parmesan until creamy.",
        ],
        ["vegetarian"],
      ),
      r(
        "panna-cotta",
        "Panna Cotta",
        "Panna cotta",
        "Silky set cream dessert often served with a bright berry or caramel sauce.",
        "dessert",
        [
          { name: "cream", quantity: 500, unit: "ml" },
          { name: "sugar", quantity: 80, unit: "g" },
          { name: "gelatin", quantity: 8, unit: "g" },
          { name: "vanilla", quantity: 1, unit: "piece" },
        ],
        [
          "1. Bloom gelatin in cold water.",
          "2. Warm cream with sugar and vanilla, then dissolve gelatin.",
          "3. Pour into moulds and chill until softly set.",
        ],
        ["vegetarian"],
      ),
    ],
    moreDrinks: [
      drink(
        "Chianti",
        "Chianti",
        "wine",
        true,
        "Classic Tuscan red that pairs well with tomato-rich pasta dishes.",
      ),
      drink(
        "Peroni / Italian Lager",
        "Birra",
        "beer",
        true,
        "Crisp lager suited to pizza, fried snacks, and casual meals.",
      ),
      drink(
        "Chinotto",
        "Chinotto",
        "soft-drink",
        false,
        "Bittersweet citrus soda with a distinctive Italian herbal edge.",
      ),
    ],
  },
  status: "published",
};
