import type { AuthoredCountry } from "@/types/content";

export const krCountry: AuthoredCountry = {
  code: "kr",
  slug: "south-korea",
  name: "South Korea",
  flag: "🇰🇷",
  region: "Asia",
  introduction: "South Korean cooking layers fermented heat, toasted sesame, rice, and seasonal vegetables into communal meals where small dishes make every table feel abundant.",
  cuisineAliases: ["Korean restaurant", "Koreaans restaurant", "Korean cuisine"],
  nationalDishId: "bibimbap",
  nationalDrink: {
    name: "Sikhye",
    localName: "식혜",
    type: "soft-drink",
    alcoholic: false,
    description: "A gently sweet malted rice drink often enjoyed after a Korean meal.",
  },
  menu: {
    starter: {
      id: "pajeon",
      name: "Spring Onion Pancake",
      localName: "\ud30c\uc804",
      description: "A crisp-edged savoury pancake packed with spring onion and a light, tender batter.",
      category: "starter",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "spring onions", quantity: 400, unit: "g" },
        { name: "flour", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Whisk flour and water into a loose, smooth batter.",
        "2. Fry spring onions in a thin layer of hot oil.",
        "3. Pour over batter and turn once until crisp.",
      ],
    },
    main: {
      id: "bibimbap",
      name: "Mixed Rice Bowl",
      localName: "\ube44\ube54\ubc25",
      description: "A widely considered Korean favourite: warm rice crowned with vegetables, egg, and gochujang.",
      category: "main",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "short-grain rice", quantity: 400, unit: "g" },
        { name: "gochujang", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Prepare each vegetable separately to keep colours distinct.",
        "2. Place warm rice in bowls and arrange toppings neatly.",
        "3. Add egg and gochujang, then mix at the table.",
      ],
      substitutions: ['Use gochujang from a toko; sambal is not a like-for-like substitute for its fermented sweetness.'],
    },
    side: {
      id: "kimchi",
      name: "Napa Cabbage Kimchi",
      localName: "\ubc30\ucd94\uae40\uce58",
      description: "Fermented napa cabbage delivers sour, spicy crunch and essential depth to a Korean spread.",
      category: "side",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "napa cabbage", quantity: 400, unit: "g" },
        { name: "gochugaru", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Salt the cabbage until pliable, then rinse well.",
        "2. Mix it with chilli flakes, garlic, and ginger.",
        "3. Pack tightly and ferment until pleasantly tangy.",
      ],
    },
    dessert: {
      id: "hotteok",
      name: "Brown Sugar Pancakes",
      localName: "\ud638\ub5a1",
      description: "Warm griddled dough filled with melting brown sugar, cinnamon, and chopped nuts.",
      category: "dessert",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "flour", quantity: 400, unit: "g" },
        { name: "brown sugar", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Mix and proof a soft yeast dough until doubled.",
        "2. Enclose sugar and nuts inside small dough rounds.",
        "3. Press and fry gently until the filling melts.",
      ],
    },
    drink: {
      name: "Sikhye",
      localName: "식혜",
      type: "soft-drink",
      alcoholic: false,
      description: "A gently sweet malted rice drink often enjoyed after a Korean meal.",
    },
    moreRecipes: [
      {
        id: "bulgogi",
        name: "Bulgogi",
        localName: "불고기",
        description:
          "Thinly sliced beef marinated in soy, pear, and sesame, then quickly grilled.",
        category: "main",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["contains-meat"],
        ingredients: [
          { name: "ribeye or sirloin", quantity: 600, unit: "g" },
          { name: "soy sauce", quantity: 60, unit: "ml" },
          { name: "Asian pear", quantity: 0.5, unit: "piece" },
          { name: "sesame oil", quantity: 15, unit: "ml" },
        ],
        steps: [
          "1. Slice beef thinly and marinate with soy, grated pear, garlic, and sesame oil.",
          "2. Grill or pan-sear quickly over high heat.",
          "3. Serve with rice, lettuce wraps, and ssamjang.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Bulgogi",
      },
      {
        id: "tteokbokki",
        name: "Spicy Rice Cakes",
        localName: "떡볶이",
        description:
          "Chewy rice cakes simmered in a sweet-spicy gochujang sauce with fish cakes.",
        category: "snack",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["contains-meat"],
        ingredients: [
          { name: "cylindrical rice cakes", quantity: 400, unit: "g" },
          { name: "gochujang", quantity: 40, unit: "g" },
          { name: "fish cakes", quantity: 150, unit: "g" },
          { name: "spring onions", quantity: 3, unit: "pieces" },
        ],
        steps: [
          "1. Soften rice cakes in warm water if refrigerated.",
          "2. Simmer gochujang, sugar, and stock into a glossy sauce.",
          "3. Add rice cakes and fish cakes until chewy and coated; finish with spring onion.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Tteokbokki",
      },
      {
        id: "kimchi-jjigae",
        name: "Kimchi Stew",
        localName: "김치찌개",
        description:
          "Bubbling stew of aged kimchi, pork or tofu, and gochugaru in a deep red broth.",
        category: "main",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["contains-meat"],
        ingredients: [
          { name: "aged kimchi", quantity: 300, unit: "g" },
          { name: "pork belly", quantity: 200, unit: "g" },
          { name: "tofu", quantity: 200, unit: "g" },
          { name: "gochugaru", quantity: 10, unit: "g" },
        ],
        steps: [
          "1. Stir-fry kimchi and pork until the edges caramelise.",
          "2. Add water or stock and gochugaru; simmer until bold and sour-spicy.",
          "3. Nestle in tofu and spring onions for the last few minutes.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Kimchi-jjigae",
      },
    ],
  },
  status: "published",
};
