import type { AuthoredCountry } from "@/types/content";

export const krCountry: AuthoredCountry = {
  code: "kr",
  slug: "south-korea",
  name: "South Korea",
  flag: "🇰🇷",
  region: "Asia",
  introduction: "South Korean cooking layers fermented heat, toasted sesame, rice, and seasonal vegetables into communal meals where small dishes make every table feel abundant.",
  cuisineAliases: ["Korean restaurant", "Koreaans restaurant", "Korean cuisine"],
  nationalDishId: "bibimbap",
  nationalDrink: {
    name: "Sikhye",
    localName: "식혜",
    type: "soft-drink",
    alcoholic: false,
    description: "A gently sweet malted rice drink often enjoyed after a Korean meal.",
  },
  menu: {
    starter: {
      id: "pajeon",
      name: "Spring Onion Pancake",
      localName: "\ud30c\uc804",
      description: "A crisp-edged savoury pancake packed with spring onion and a light, tender batter.",
      category: "starter",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "spring onions", quantity: 400, unit: "g" },
        { name: "flour", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Whisk flour and water into a loose, smooth batter.",
        "2. Fry spring onions in a thin layer of hot oil.",
        "3. Pour over batter and turn once until crisp.",
      ],
    },
    main: {
      id: "bibimbap",
      name: "Mixed Rice Bowl",
      localName: "\ube44\ube54\ubc25",
      description: "A widely considered Korean favourite: warm rice crowned with vegetables, egg, and gochujang.",
      category: "main",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "short-grain rice", quantity: 400, unit: "g" },
        { name: "gochujang", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Prepare each vegetable separately to keep colours distinct.",
        "2. Place warm rice in bowls and arrange toppings neatly.",
        "3. Add egg and gochujang, then mix at the table.",
      ],
      substitutions: ['Use gochujang from a toko; sambal is not a like-for-like substitute for its fermented sweetness.'],
    },
    side: {
      id: "kimchi",
      name: "Napa Cabbage Kimchi",
      localName: "\ubc30\ucd94\uae40\uce58",
      description: "Fermented napa cabbage delivers sour, spicy crunch and essential depth to a Korean spread.",
      category: "side",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "napa cabbage", quantity: 400, unit: "g" },
        { name: "gochugaru", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Salt the cabbage until pliable, then rinse well.",
        "2. Mix it with chilli flakes, garlic, and ginger.",
        "3. Pack tightly and ferment until pleasantly tangy.",
      ],
    },
    dessert: {
      id: "hotteok",
      name: "Brown Sugar Pancakes",
      localName: "\ud638\ub5a1",
      description: "Warm griddled dough filled with melting brown sugar, cinnamon, and chopped nuts.",
      category: "dessert",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "flour", quantity: 400, unit: "g" },
        { name: "brown sugar", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Mix and proof a soft yeast dough until doubled.",
        "2. Enclose sugar and nuts inside small dough rounds.",
        "3. Press and fry gently until the filling melts.",
      ],
    },
    drink: {
      name: "Sikhye",
      localName: "식혜",
      type: "soft-drink",
      alcoholic: false,
      description: "A gently sweet malted rice drink often enjoyed after a Korean meal.",
    },
  },
  status: "published",
};
