import type { AuthoredCountry } from "@/types/content";

export const ngCountry: AuthoredCountry = {
  code: "ng",
  slug: "nigeria",
  name: "Nigeria",
  flag: "🇳🇬",
  region: "Africa",
  introduction: "Nigerian cooking is boldly seasoned and generous, bringing together rice, cassava, beans, leafy greens, peppers, and richly flavoured soups in distinct regional styles.",
  cuisineAliases: ["Nigerian restaurant", "Nigeriaans restaurant", "Nigerian cuisine"],
  nationalDishId: "jollof-rice",
  nationalDrink: {
    name: "Zobo",
    localName: "Zobo",
    type: "soft-drink",
    alcoholic: false,
    description: "A chilled hibiscus drink, often infused with ginger and pineapple.",
  },
  menu: {
    starter: {
      id: "akara",
      name: "Black-Eyed Pea Fritters",
      localName: "\u00c0k\u00e0r\u00e0",
      description: "Crisp, airy fritters made from blended black-eyed peas, onion, and pepper.",
      category: "starter",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "black-eyed peas", quantity: 400, unit: "g" },
        { name: "onion", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Soak and blend the peas with onion and pepper.",
        "2. Whip the batter briefly to incorporate lightness.",
        "3. Fry spoonfuls until golden and crisp outside.",
      ],
    },
    main: {
      id: "jollof-rice",
      name: "Nigerian Jollof Rice",
      localName: "Jollof rice",
      description: "A widely considered Nigerian party classic of smoky tomato rice with pepper and aromatic spices.",
      category: "main",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "long-grain rice", quantity: 400, unit: "g" },
        { name: "tomatoes", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Blend tomatoes, peppers, and onion into a smooth base.",
        "2. Fry the sauce until concentrated and richly coloured.",
        "3. Steam the rice in the sauce until tender and separate.",
      ],
      substitutions: ['Use long-grain rice from the supermarket; Scotch bonnet peppers can be replaced with madame Jeanette.'],
    },
    side: {
      id: "dodo",
      name: "Fried Plantains",
      localName: "D\u00f2d\u00f2",
      description: "Ripe plantain slices fry into caramelised, soft-centred bites with a savoury edge.",
      category: "side",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "ripe plantains", quantity: 400, unit: "g" },
        { name: "vegetable oil", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Peel plantains and cut them into thick diagonal slices.",
        "2. Heat oil until a test piece sizzles immediately.",
        "3. Fry in batches until browned and drain briefly.",
      ],
    },
    dessert: {
      id: "chin-chin",
      name: "Crunchy Chin Chin",
      localName: "Chin chin",
      description: "Small lightly sweet fried pastry bites with nutmeg and a cheerful crunchy texture.",
      category: "dessert",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "flour", quantity: 400, unit: "g" },
        { name: "nutmeg", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Rub butter into flour with sugar and nutmeg.",
        "2. Bring together a firm dough and cut small pieces.",
        "3. Fry in batches until crisp and pale golden.",
      ],
    },
    drink: {
      name: "Zobo",
      localName: "Zobo",
      type: "soft-drink",
      alcoholic: false,
      description: "A chilled hibiscus drink, often infused with ginger and pineapple.",
    },
  },
  status: "published",
};
