import type { AuthoredCountry } from "@/types/content";

export const ngCountry: AuthoredCountry = {
  code: "ng",
  slug: "nigeria",
  name: "Nigeria",
  flag: "🇳🇬",
  region: "Africa",
  introduction: "Nigerian cooking is boldly seasoned and generous, bringing together rice, cassava, beans, leafy greens, peppers, and richly flavoured soups in distinct regional styles.",
  cuisineAliases: ["Nigerian restaurant", "Nigeriaans restaurant", "Nigerian cuisine"],
  nationalDishId: "jollof-rice",
  nationalDrink: {
    name: "Zobo",
    localName: "Zobo",
    type: "soft-drink",
    alcoholic: false,
    description: "A chilled hibiscus drink, often infused with ginger and pineapple.",
  },
  menu: {
    starter: {
      id: "akara",
      name: "Black-Eyed Pea Fritters",
      localName: "\u00c0k\u00e0r\u00e0",
      description: "Crisp, airy fritters made from blended black-eyed peas, onion, and pepper.",
      category: "starter",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "black-eyed peas", quantity: 400, unit: "g" },
        { name: "onion", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Soak and blend the peas with onion and pepper.",
        "2. Whip the batter briefly to incorporate lightness.",
        "3. Fry spoonfuls until golden and crisp outside.",
      ],
    },
    main: {
      id: "jollof-rice",
      name: "Nigerian Jollof Rice",
      localName: "Jollof rice",
      description: "A widely considered Nigerian party classic of smoky tomato rice with pepper and aromatic spices.",
      category: "main",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "long-grain rice", quantity: 400, unit: "g" },
        { name: "tomatoes", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Blend tomatoes, peppers, and onion into a smooth base.",
        "2. Fry the sauce until concentrated and richly coloured.",
        "3. Steam the rice in the sauce until tender and separate.",
      ],
      substitutions: ['Use long-grain rice from the supermarket; Scotch bonnet peppers can be replaced with madame Jeanette.'],
    },
    side: {
      id: "dodo",
      name: "Fried Plantains",
      localName: "D\u00f2d\u00f2",
      description: "Ripe plantain slices fry into caramelised, soft-centred bites with a savoury edge.",
      category: "side",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "ripe plantains", quantity: 400, unit: "g" },
        { name: "vegetable oil", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Peel plantains and cut them into thick diagonal slices.",
        "2. Heat oil until a test piece sizzles immediately.",
        "3. Fry in batches until browned and drain briefly.",
      ],
    },
    dessert: {
      id: "chin-chin",
      name: "Crunchy Chin Chin",
      localName: "Chin chin",
      description: "Small lightly sweet fried pastry bites with nutmeg and a cheerful crunchy texture.",
      category: "dessert",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "flour", quantity: 400, unit: "g" },
        { name: "nutmeg", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Rub butter into flour with sugar and nutmeg.",
        "2. Bring together a firm dough and cut small pieces.",
        "3. Fry in batches until crisp and pale golden.",
      ],
    },
    drink: {
      name: "Zobo",
      localName: "Zobo",
      type: "soft-drink",
      alcoholic: false,
      description: "A chilled hibiscus drink, often infused with ginger and pineapple.",
    },
    moreRecipes: [
      {
        id: "egusi-soup",
        name: "Egusi Soup",
        localName: "Egusi",
        description:
          "Melon-seed thickened soup with leafy greens and assorted meats or fish.",
        category: "main",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["contains-meat"],
        ingredients: [
          { name: "ground egusi melon seeds", quantity: 200, unit: "g" },
          { name: "palm oil", quantity: 60, unit: "ml" },
          { name: "spinach or ugu leaves", quantity: 300, unit: "g" },
          { name: "assorted meat or fish", quantity: 500, unit: "g" },
        ],
        steps: [
          "1. Cook meats in seasoned stock until tender.",
          "2. Fry ground egusi in palm oil into soft curds, then add stock.",
          "3. Stir in greens at the end and serve with fufu or pounded yam.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Egusi_soup",
      },
      {
        id: "suya",
        name: "Suya Skewers",
        localName: "Suya",
        description:
          "Spicy peanut-rubbed beef skewers grilled street-style with onions and tomato.",
        category: "snack",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["contains-meat"],
        ingredients: [
          { name: "beef sirloin", quantity: 600, unit: "g" },
          { name: "suya spice or ground peanuts with cayenne", quantity: 50, unit: "g" },
          { name: "onion", quantity: 1, unit: "piece" },
          { name: "groundnut oil", quantity: 30, unit: "ml" },
        ],
        steps: [
          "1. Slice beef thin, oil lightly, and coat in suya spice.",
          "2. Thread onto skewers and grill over high heat.",
          "3. Serve with sliced onion, tomato, and extra spice.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Suya",
      },
      {
        id: "puff-puff",
        name: "Puff-Puff",
        localName: "Puff-puff",
        description:
          "Yeasted deep-fried dough balls that are lightly sweet and cloud-soft inside.",
        category: "dessert",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 35,
        difficulty: "medium",
        dietaryLabels: ["vegetarian"],
        ingredients: [
          { name: "flour", quantity: 350, unit: "g" },
          { name: "sugar", quantity: 60, unit: "g" },
          { name: "instant yeast", quantity: 7, unit: "g" },
          { name: "warm water", quantity: 250, unit: "ml" },
        ],
        steps: [
          "1. Mix a sticky yeasted batter and proof until doubled.",
          "2. Scoop spoonfuls into hot oil and fry, turning, until mahogany brown.",
          "3. Drain and serve warm, plain or with a dusting of sugar.",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/Puff_puff",
      },
    ],
  },
  status: "published",
};
