import type { Country } from "@/types/content";

export const nlCountry: Country = {
  code: "nl",
  slug: "netherlands",
  name: "Netherlands",
  flag: "🇳🇱",
  region: "Europe",
  introduction:
    "Dutch cooking makes much of sturdy vegetables, dairy, potatoes, and the North Sea. Familiar everyday dishes become deeply comforting when the weather turns cool.",
  cuisineAliases: ["Dutch restaurant", "Nederlands restaurant", "Hollandse keuken"],
  nationalDishId: "stamppot-boerenkool",
  nationalDrink: {
    name: "Jenever",
    localName: "Jenever",
    type: "spirit",
    alcoholic: true,
    description: "A juniper-led Dutch spirit, traditionally sipped chilled.",
  },
  menu: {
    starter: {
      id: "bitterballen",
      name: "Bitterballen",
      description: "Crisp little croquettes with a creamy beef filling.",
      category: "starter",
      servings: 4,
      prepMinutes: 30,
      cookMinutes: 15,
      difficulty: "medium",
      dietaryLabels: [],
      ingredients: [
        { name: "cooked beef", quantity: 250, unit: "g" },
        { name: "butter", quantity: 40, unit: "g" },
        { name: "flour", quantity: 50, unit: "g" },
        { name: "beef stock", quantity: 300, unit: "ml" },
        { name: "breadcrumbs", quantity: 120, unit: "g" },
      ],
      steps: [
        "1. Make a thick roux with butter, flour, stock, and shredded beef; chill until firm.",
        "2. Roll the cold filling into 16 balls, then coat with beaten egg and breadcrumbs.",
        "3. Fry at 175°C until deeply golden and drain briefly.",
      ],
      servingSuggestion: "Serve hot with sharp Dutch mustard.",
    },
    main: {
      id: "stamppot-boerenkool",
      name: "Kale Stamppot",
      localName: "Boerenkoolstamppot",
      description:
        "Mashed potato and curly kale with smoky sausage, an iconic winter plate.",
      category: "main",
      servings: 4,
      prepMinutes: 15,
      cookMinutes: 30,
      difficulty: "easy",
      dietaryLabels: ["gluten-free"],
      ingredients: [
        { name: "floury potatoes", quantity: 1200, unit: "g" },
        { name: "curly kale", quantity: 400, unit: "g" },
        { name: "rookworst", quantity: 1, unit: "piece" },
        { name: "milk", quantity: 120, unit: "ml" },
        { name: "butter", quantity: 40, unit: "g" },
      ],
      steps: [
        "1. Boil potatoes; add kale over them for the final 10 minutes so it steams tender.",
        "2. Warm the sausage according to its packet while the vegetables cook.",
        "3. Drain, mash with warm milk and butter, season, and serve with sliced sausage.",
      ],
      substitutions: [
        "Use a smoked sausage from a Dutch supermarket; kielbasa is a close alternative.",
      ],
      drinkPairing: "A pale Dutch lager keeps the meal light.",
    },
    side: {
      id: "zoetzure-rode-kool",
      name: "Sweet-Sour Red Cabbage",
      localName: "Rode kool",
      description: "Slow-braised cabbage brightened with apple and vinegar.",
      category: "side",
      servings: 4,
      prepMinutes: 10,
      cookMinutes: 40,
      difficulty: "easy",
      dietaryLabels: ["vegan", "gluten-free"],
      ingredients: [
        { name: "red cabbage", quantity: 700, unit: "g" },
        { name: "apple", quantity: 1, unit: "piece" },
        { name: "apple cider vinegar", quantity: 30, unit: "ml" },
        { name: "brown sugar", quantity: 15, unit: "g" },
      ],
      steps: [
        "1. Shred cabbage and dice the apple.",
        "2. Put everything in a covered pan with 100 ml water.",
        "3. Simmer gently until tender, stirring once or twice.",
      ],
    },
    dessert: {
      id: "appeltaart",
      name: "Dutch Apple Pie",
      localName: "Appeltaart",
      description: "High-crusted apple pie scented with cinnamon and lemon.",
      category: "dessert",
      servings: 8,
      prepMinutes: 30,
      cookMinutes: 55,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "flour", quantity: 300, unit: "g" },
        { name: "butter", quantity: 180, unit: "g" },
        { name: "apples", quantity: 900, unit: "g" },
        { name: "sugar", quantity: 150, unit: "g" },
        { name: "cinnamon", quantity: 8, unit: "g" },
      ],
      steps: [
        "1. Rub flour, butter, and sugar into dough and line a 24 cm tin.",
        "2. Toss sliced apples with cinnamon and fill the case.",
        "3. Add pastry strips and bake at 180°C until browned.",
      ],
      servingSuggestion: "Offer a generous spoonful of whipped cream.",
    },
    drink: {
      name: "Dutch Lager",
      type: "beer",
      alcoholic: true,
      description: "A clean, light pilsner commonly poured alongside snacks and dinner.",
    },
  },
  status: "published",
};
