import type { AuthoredCountry } from "@/types/content";

export const phCountry: AuthoredCountry = {
  code: "ph",
  slug: "philippines",
  name: "Philippines",
  flag: "🇵🇭",
  region: "Asia",
  introduction: "Filipino cooking blends sour, salty, sweet, and savoury flavours through vinegars, coconut, rice, noodles, and abundant seafood, shaped by many islands and histories.",
  cuisineAliases: ["Filipino restaurant", "Filipijns restaurant", "Philippine cuisine"],
  nationalDishId: "chicken-adobo",
  nationalDrink: {
    name: "Calamansi Juice",
    localName: "Calamansi juice",
    type: "soft-drink",
    alcoholic: false,
    description: "Tart calamansi juice sweetened and poured over ice is refreshing with savoury food.",
  },
  menu: {
    starter: {
      id: "lumpia",
      name: "Fresh Lumpia",
      localName: "Lumpiang sariwa",
      description: "Soft wrappers hold crisp vegetables, herbs, and a savoury-sweet garlic peanut sauce.",
      category: "starter",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "rice paper wrappers", quantity: 400, unit: "g" },
        { name: "cabbage", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Cook the vegetable filling until just tender.",
        "2. Roll portions tightly in softened wrappers.",
        "3. Serve with the garlic peanut sauce alongside.",
      ],
    },
    main: {
      id: "chicken-adobo",
      name: "Chicken Adobo",
      localName: "Adobong manok",
      description: "A widely considered Filipino classic: chicken braised in vinegar, soy sauce, garlic, and peppercorns.",
      category: "main",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["gluten-free"],
      ingredients: [
        { name: "chicken thighs", quantity: 400, unit: "g" },
        { name: "cane vinegar", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Marinate chicken with vinegar, soy, garlic, and peppercorns.",
        "2. Simmer until tender and the sauce becomes glossy.",
        "3. Brown the chicken briefly and spoon over the reduced sauce.",
      ],
      substitutions: ['Use rice vinegar and gluten-free tamari from a toko if cane vinegar or Filipino soy sauce is unavailable.'],
    },
    side: {
      id: "atchara",
      name: "Pickled Green Papaya",
      localName: "Atchara",
      description: "Sweet-tangy pickled green papaya provides bright crunch beside rich braised dishes.",
      category: "side",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "green papaya", quantity: 400, unit: "g" },
        { name: "cane vinegar", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Salt the shredded papaya and squeeze out excess moisture.",
        "2. Warm vinegar with sugar and ginger until dissolved.",
        "3. Pour over vegetables and chill until thoroughly cold.",
      ],
    },
    dessert: {
      id: "halo-halo",
      name: "Shaved Ice Sundae",
      localName: "Halo-halo",
      description: "A colourful chilled dessert of shaved ice, sweet beans, fruit, milk, and creamy toppings.",
      category: "dessert",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "shaved ice", quantity: 400, unit: "g" },
        { name: "sweetened condensed milk", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Layer sweet beans and fruit in tall chilled glasses.",
        "2. Pile over shaved ice and drizzle with milk.",
        "3. Add ice cream or ube topping just before serving.",
      ],
    },
    drink: {
      name: "Calamansi Juice",
      localName: "Calamansi juice",
      type: "soft-drink",
      alcoholic: false,
      description: "Tart calamansi juice sweetened and poured over ice is refreshing with savoury food.",
    },
  },
  status: "published",
};
