import type { Country } from "@/types/content";

export const ptCountry: Country = {
  code: "pt",
  slug: "portugal",
  name: "Portugal",
  flag: "🇵🇹",
  region: "Europe",
  introduction: "Portuguese food draws on the Atlantic with salt cod, shellfish, olive oil, and grilled fish, while egg-rich sweets and warming stews reflect deep regional traditions.",
  cuisineAliases: ["Portuguese restaurant", "Portugees restaurant", "Portuguese cuisine"],
  nationalDishId: "bacalhau-a-bras",
  nationalDrink: {
    name: "Vinho Verde",
    localName: "Vinho Verde",
    type: "wine",
    alcoholic: true,
    description: "This lightly lively northern Portuguese wine is bright with seafood and salty dishes.",
  },
  menu: {
    starter: {
      id: "caldo-verde",
      name: "Kale and Potato Soup",
      localName: "Caldo verde",
      description: "Velvety potato soup threaded with finely shredded kale and often finished with smoky sausage.",
      category: "starter",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["gluten-free"],
      ingredients: [
        { name: "potatoes", quantity: 400, unit: "g" },
        { name: "kale", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Cook potatoes and onion in stock until completely soft.",
        "2. Blend until smooth and return the soup to the pot.",
        "3. Add kale ribbons and cook only until tender.",
      ],
    },
    main: {
      id: "bacalhau-a-bras",
      name: "Salt Cod and Potato Scramble",
      localName: "Bacalhau \u00e0 Br\u00e1s",
      description: "A widely considered Portuguese favourite of shredded salt cod, matchstick potatoes, onion, and egg.",
      category: "main",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["gluten-free"],
      ingredients: [
        { name: "salt cod", quantity: 400, unit: "g" },
        { name: "eggs", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Soak salt cod thoroughly, then flake it into pieces.",
        "2. Soften onion and fold in crisp potato sticks.",
        "3. Stir through egg gently until just softly set.",
      ],
      substitutions: ['Use bakkeljauw or well-soaked stockfish for salt cod, plus ready-cut frietjes if preferred.'],
    },
    side: {
      id: "piri-piri-peppers",
      name: "Piri-Piri Roasted Peppers",
      localName: "Pimentos assados",
      description: "Sweet roasted peppers dressed with garlic, olive oil, and a lively touch of chilli.",
      category: "side",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegan"],
      ingredients: [
        { name: "red peppers", quantity: 400, unit: "g" },
        { name: "olive oil", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Char peppers until their skins blacken in places.",
        "2. Cover to steam, then peel and slice them.",
        "3. Dress with garlic, oil, and a little chilli.",
      ],
    },
    dessert: {
      id: "pastel-de-nata",
      name: "Custard Tarts",
      localName: "Past\u00e9is de nata",
      description: "Crisp pastry cups filled with creamy egg custard and baked until caramel-speckled.",
      category: "dessert",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "puff pastry", quantity: 400, unit: "g" },
        { name: "egg yolks", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Line small tins with rolled puff pastry.",
        "2. Cook milk, sugar, and yolks into a smooth custard.",
        "3. Bake very hot until the tops spot and blister.",
      ],
    },
    drink: {
      name: "Vinho Verde",
      localName: "Vinho Verde",
      type: "wine",
      alcoholic: true,
      description: "This lightly lively northern Portuguese wine is bright with seafood and salty dishes.",
    },
  },
  status: "published",
};
