import type { AuthoredCountry } from "@/types/content";
import { drink } from "./content-helpers";

export const thCountry: AuthoredCountry = {
  code: "th",
  slug: "thailand",
  name: "Thailand",
  flag: "🇹🇭",
  region: "Asia",
  introduction: "Thai cooking brings bright herbs, chilli heat, sour lime, fragrant rice, and savoury depth into lively dishes that balance several flavours in every bite.",
  cuisineAliases: ["Thai restaurant", "Thais restaurant", "Thai cuisine"],
  nationalDishId: "pad-thai",
  nationalDrink: drink(
    "Thai Iced Tea",
    "ชาเย็น",
    "soft-drink",
    false,
    "Sweet, creamy Thai iced tea brings relief alongside spicy food.",
  ),
  menu: {
    starter: {
      id: "som-tam",
      name: "Green Papaya Salad",
      localName: "\u0e2a\u0e49\u0e21\u0e15\u0e33",
      description: "A crisp, punchy salad where green papaya meets lime, chilli, peanuts, and savoury dressing.",
      category: "starter",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian", "vegan"],
      ingredients: [
        { name: "green papaya", quantity: 400, unit: "g" },
        { name: "lime", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Pound garlic and chilli lightly in a mortar.",
        "2. Toss shredded papaya with lime juice and seasoning.",
        "3. Finish with peanuts just before serving.",
      ],
    },
    main: {
      id: "pad-thai",
      name: "Stir-Fried Rice Noodles",
      localName: "\u0e1c\u0e31\u0e14\u0e44\u0e17\u0e22",
      description: "A widely considered Thai classic of chewy rice noodles, tamarind, tofu, egg, and peanuts.",
      category: "main",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian"],
      ingredients: [
        { name: "rice noodles", quantity: 400, unit: "g" },
        { name: "tamarind paste", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Soak the noodles until flexible but not soft.",
        "2. Stir-fry aromatics and tofu before adding noodles and sauce.",
        "3. Fold in egg, sprouts, and peanuts just before serving.",
      ],
      substitutions: ['Asian supermarkets sell tamarind paste and rice noodles; use extra firm tofu from Albert Heijn.'],
    },
    side: {
      id: "cucumber-relish",
      name: "Cucumber Relish",
      localName: "\u0e2d\u0e32\u0e08\u0e32\u0e14",
      description: "Cool cucumber relish with vinegar and shallot offers a sharp, refreshing counterpoint.",
      category: "side",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian", "vegan"],
      ingredients: [
        { name: "cucumber", quantity: 400, unit: "g" },
        { name: "rice vinegar", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Slice cucumber and shallot very thinly.",
        "2. Dissolve sugar in vinegar with a little water.",
        "3. Pour over vegetables and chill before serving.",
      ],
    },
    dessert: {
      id: "mango-sticky-rice",
      name: "Mango Sticky Rice",
      localName: "\u0e02\u0e49\u0e32\u0e27\u0e40\u0e2b\u0e19\u0e35\u0e22\u0e27\u0e21\u0e30\u0e21\u0e48\u0e27\u0e07",
      description: "Tender sticky rice scented with coconut milk and served beside ripe, juicy mango.",
      category: "dessert",
      servings: 4,
      prepMinutes: 20,
      cookMinutes: 30,
      difficulty: "medium",
      dietaryLabels: ["vegetarian", "vegan"],
      ingredients: [
        { name: "glutinous rice", quantity: 400, unit: "g" },
        { name: "coconut milk", quantity: 2, unit: "pieces" },
      ],
      steps: [
        "1. Steam soaked rice until the grains are tender.",
        "2. Stir warm coconut milk with sugar and salt.",
        "3. Rest the rice, then serve with sliced mango.",
      ],
    },
    drink: drink(
      "Thai Iced Tea",
      "ชาเย็น",
      "soft-drink",
      false,
      "Sweet, creamy Thai iced tea brings relief alongside spicy food.",
    ),
    moreRecipes: [
      {
        id: "tom-yum-goong",
        name: "Hot and Sour Prawn Soup",
        localName: "ต้มยำกุ้ง",
        description:
          "A fragrant, spicy-sour broth with prawns, lemongrass, galangal, and lime leaves.",
        category: "starter",
        servings: 4,
        prepMinutes: 15,
        cookMinutes: 20,
        difficulty: "medium",
        dietaryLabels: ["contains-meat"],
        ingredients: [
          { name: "prawns", quantity: 400, unit: "g" },
          { name: "lemongrass", quantity: 2, unit: "stalks" },
          { name: "galangal", quantity: 30, unit: "g" },
          { name: "lime leaves", quantity: 6, unit: "pieces" },
        ],
        steps: [
          "1. Simmer aromatics in stock until fragrant.",
          "2. Add prawns and cook just until pink.",
          "3. Season with lime juice, fish sauce, and chilli to taste.",
        ],
      },
      {
        id: "green-curry-chicken",
        name: "Green Curry Chicken",
        localName: "แกงเขียวหวานไก่",
        description:
          "Coconut green curry with tender chicken, Thai eggplant, and sweet basil.",
        category: "main",
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 25,
        difficulty: "medium",
        dietaryLabels: ["contains-meat"],
        ingredients: [
          { name: "chicken thigh", quantity: 700, unit: "g" },
          { name: "green curry paste", quantity: 60, unit: "g" },
          { name: "coconut milk", quantity: 400, unit: "ml" },
          { name: "Thai basil", quantity: 30, unit: "g" },
        ],
        steps: [
          "1. Fry curry paste in a little coconut cream until aromatic.",
          "2. Add chicken, remaining coconut milk, and simmer until tender.",
          "3. Finish with basil and serve with jasmine rice.",
        ],
      },
      {
        id: "thai-spring-rolls",
        name: "Fresh Spring Rolls",
        localName: "ปอเปี๊ยะสด",
        description:
          "Rice-paper rolls packed with herbs, noodles, and crisp vegetables for snacking.",
        category: "snack",
        servings: 4,
        prepMinutes: 30,
        cookMinutes: 0,
        difficulty: "easy",
        dietaryLabels: ["vegetarian", "vegan"],
        ingredients: [
          { name: "rice paper wrappers", quantity: 12, unit: "pieces" },
          { name: "rice vermicelli", quantity: 150, unit: "g" },
          { name: "lettuce", quantity: 100, unit: "g" },
          { name: "fresh herbs", quantity: 40, unit: "g" },
        ],
        steps: [
          "1. Soften rice paper briefly in warm water.",
          "2. Layer noodles, lettuce, and herbs near the centre.",
          "3. Roll tightly and serve with a sweet-chilli or peanut dip.",
        ],
      },
    ],
    moreDrinks: [
      drink(
        "Singha Beer",
        "สิงห์",
        "beer",
        true,
        "Crisp Thai lager that cools spicy curries and street snacks.",
      ),
      drink(
        "Mekhong",
        "แม่โขง",
        "spirit",
        true,
        "Sweet herbal Thai spirit often mixed with soda and lime.",
      ),
      drink(
        "Nam Manao",
        "น้ำมะนาว",
        "soft-drink",
        false,
        "Fresh lime soda, lightly sweetened and very refreshing.",
      ),
    ],
  },
  status: "published",
};
